// Code generated by protoc-gen-go.
// source: services/unit_service.proto
// DO NOT EDIT!

/*
Package Services is a generated protocol buffer package.

It is generated from these files:
	services/unit_service.proto

It has these top-level messages:
	FrameBytes
*/
package Services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import DataTypes2 "datatypes"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FrameBytes struct {
	FrameData []byte `protobuf:"bytes,1,opt,name=frameData,proto3" json:"frameData,omitempty"`
}

func (m *FrameBytes) Reset()                    { *m = FrameBytes{} }
func (m *FrameBytes) String() string            { return proto.CompactTextString(m) }
func (*FrameBytes) ProtoMessage()               {}
func (*FrameBytes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*FrameBytes)(nil), "Services.FrameBytes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for UnitService service

type UnitServiceClient interface {
	OpenDoor(ctx context.Context, in *DataTypes2.Location, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	GetVideoStream(ctx context.Context, in *DataTypes2.Location, opts ...grpc.CallOption) (UnitService_GetVideoStreamClient, error)
	UpdateLocation(ctx context.Context, in *DataTypes2.Location, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type unitServiceClient struct {
	cc *grpc.ClientConn
}

func NewUnitServiceClient(cc *grpc.ClientConn) UnitServiceClient {
	return &unitServiceClient{cc}
}

func (c *unitServiceClient) OpenDoor(ctx context.Context, in *DataTypes2.Location, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/Services.UnitService/OpenDoor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unitServiceClient) GetVideoStream(ctx context.Context, in *DataTypes2.Location, opts ...grpc.CallOption) (UnitService_GetVideoStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_UnitService_serviceDesc.Streams[0], c.cc, "/Services.UnitService/GetVideoStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &unitServiceGetVideoStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UnitService_GetVideoStreamClient interface {
	Recv() (*FrameBytes, error)
	grpc.ClientStream
}

type unitServiceGetVideoStreamClient struct {
	grpc.ClientStream
}

func (x *unitServiceGetVideoStreamClient) Recv() (*FrameBytes, error) {
	m := new(FrameBytes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *unitServiceClient) UpdateLocation(ctx context.Context, in *DataTypes2.Location, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/Services.UnitService/UpdateLocation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UnitService service

type UnitServiceServer interface {
	OpenDoor(context.Context, *DataTypes2.Location) (*google_protobuf.Empty, error)
	GetVideoStream(*DataTypes2.Location, UnitService_GetVideoStreamServer) error
	UpdateLocation(context.Context, *DataTypes2.Location) (*google_protobuf.Empty, error)
}

func RegisterUnitServiceServer(s *grpc.Server, srv UnitServiceServer) {
	s.RegisterService(&_UnitService_serviceDesc, srv)
}

func _UnitService_OpenDoor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataTypes2.Location)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitServiceServer).OpenDoor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Services.UnitService/OpenDoor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitServiceServer).OpenDoor(ctx, req.(*DataTypes2.Location))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnitService_GetVideoStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DataTypes2.Location)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UnitServiceServer).GetVideoStream(m, &unitServiceGetVideoStreamServer{stream})
}

type UnitService_GetVideoStreamServer interface {
	Send(*FrameBytes) error
	grpc.ServerStream
}

type unitServiceGetVideoStreamServer struct {
	grpc.ServerStream
}

func (x *unitServiceGetVideoStreamServer) Send(m *FrameBytes) error {
	return x.ServerStream.SendMsg(m)
}

func _UnitService_UpdateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataTypes2.Location)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnitServiceServer).UpdateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Services.UnitService/UpdateLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnitServiceServer).UpdateLocation(ctx, req.(*DataTypes2.Location))
	}
	return interceptor(ctx, in, info, handler)
}

var _UnitService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Services.UnitService",
	HandlerType: (*UnitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenDoor",
			Handler:    _UnitService_OpenDoor_Handler,
		},
		{
			MethodName: "UpdateLocation",
			Handler:    _UnitService_UpdateLocation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetVideoStream",
			Handler:       _UnitService_GetVideoStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("services/unit_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x2f, 0xcd, 0xcb, 0x2c, 0x89, 0x87, 0xf2, 0xf4, 0x0a, 0x8a, 0xf2,
	0x4b, 0xf2, 0x85, 0x38, 0x82, 0xa1, 0x92, 0x52, 0xd2, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa,
	0x60, 0xf1, 0xa4, 0xd2, 0x34, 0xfd, 0xd4, 0xdc, 0x82, 0x92, 0x4a, 0x88, 0x32, 0x29, 0x89, 0x94,
	0xc4, 0x92, 0xc4, 0x92, 0xca, 0x82, 0xd4, 0x62, 0xfd, 0x9c, 0xfc, 0xe4, 0xc4, 0x92, 0xcc, 0xfc,
	0x3c, 0x88, 0x8c, 0x92, 0x16, 0x17, 0x97, 0x5b, 0x51, 0x62, 0x6e, 0xaa, 0x53, 0x65, 0x49, 0x6a,
	0xb1, 0x90, 0x0c, 0x17, 0x67, 0x1a, 0x88, 0xe7, 0x92, 0x58, 0x92, 0x28, 0xc1, 0xa8, 0xc0, 0xa8,
	0xc1, 0x13, 0x84, 0x10, 0x30, 0x3a, 0xc5, 0xc8, 0xc5, 0x1d, 0x9a, 0x97, 0x59, 0x02, 0xb5, 0x53,
	0xc8, 0x92, 0x8b, 0xc3, 0xbf, 0x20, 0x35, 0xcf, 0x25, 0x3f, 0xbf, 0x48, 0x48, 0x58, 0x0f, 0xa4,
	0x24, 0x04, 0x64, 0x85, 0x9e, 0x0f, 0xd4, 0x0a, 0x29, 0x31, 0x3d, 0x88, 0xa3, 0xf4, 0x60, 0x8e,
	0xd2, 0x73, 0x05, 0x39, 0x4a, 0x89, 0x41, 0xc8, 0x9e, 0x8b, 0xcf, 0x3d, 0xb5, 0x24, 0x2c, 0x33,
	0x25, 0x35, 0x3f, 0xb8, 0xa4, 0x28, 0x35, 0x31, 0x17, 0xbb, 0x01, 0x22, 0x7a, 0x30, 0xff, 0xe9,
	0x21, 0x5c, 0xa9, 0xc4, 0x60, 0xc0, 0x08, 0x32, 0x20, 0xb4, 0x20, 0x25, 0xb1, 0x24, 0x15, 0xa6,
	0x96, 0x44, 0x17, 0x38, 0xf1, 0x73, 0xb1, 0xa7, 0x56, 0xe8, 0xa5, 0x17, 0x15, 0x24, 0x2f, 0x62,
	0x62, 0x0e, 0x0a, 0x71, 0x4f, 0x62, 0x03, 0x2b, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x1c,
	0x41, 0x7b, 0x82, 0x70, 0x01, 0x00, 0x00,
}
