// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/client_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Services {

  /// <summary>Holder for reflection information generated from services/client_service.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class ClientServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for services/client_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1zZXJ2aWNlcy9jbGllbnRfc2VydmljZS5wcm90bxIIU2VydmljZXMaG2dv",
            "b2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90bxoUZGF0YXR5cGVzL3VuaXQucHJv",
            "dG8aGGRhdGF0eXBlcy9sb2NhdGlvbi5wcm90bxoXZGF0YXR5cGVzL2Rldmlj",
            "ZXMucHJvdG8aHGRhdGF0eXBlcy92aXNpdF9yZWNvcmQucHJvdG8yngIKDUNs",
            "aWVudFNlcnZpY2USRwoSVXBkYXRlVmlzaXRSZWNvcmRzEhcuRGF0YVR5cGVz",
            "LlZpc2l0UmVjb3JkcxoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAEj8KC1Vw",
            "ZGF0ZVVuaXRzEhYuRGF0YVR5cGVzLlVuaXRVcGRhdGVzGhYuZ29vZ2xlLnBy",
            "b3RvYnVmLkVtcHR5IgASPwoOVXBkYXRlTG9jYXRpb24SEy5EYXRhVHlwZXMu",
            "TG9jYXRpb24aFi5nb29nbGUucHJvdG9idWYuRW1wdHkiABJCCg1VcGRhdGVE",
            "ZXZpY2VzEhcuRGF0YVR5cGVzLkRldmljZVVwZGF0ZRoWLmdvb2dsZS5wcm90",
            "b2J1Zi5FbXB0eSIAQlEKB2V4LmdycGNaQGdpdGh1Yi5jb20vRW5lYnJhL1Nl",
            "cnZpY2VDb29yZGluYXRvci9ncnBjL3NlcnZpY2VzL2NsaWVudHNlcnZpY2Wi",
            "AgNSVEdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::DataTypes.UnitReflection.Descriptor, global::DataTypes.LocationReflection.Descriptor, global::DataTypes.DevicesReflection.Descriptor, global::DataTypes.VisitRecordReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
