// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/database_service.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Services {
  public static class DatabaseSevice
  {
    static readonly string __ServiceName = "Services.DatabaseSevice";

    static readonly Marshaller<global::Services.GetPersonRequest> __Marshaller_GetPersonRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Services.GetPersonRequest.Parser.ParseFrom);
    static readonly Marshaller<global::DataTypes.Persons> __Marshaller_Persons = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DataTypes.Persons.Parser.ParseFrom);
    static readonly Marshaller<global::DataTypes.Person> __Marshaller_Person = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DataTypes.Person.Parser.ParseFrom);
    static readonly Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_Empty = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly Marshaller<global::DataTypes.Card> __Marshaller_Card = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DataTypes.Card.Parser.ParseFrom);
    static readonly Marshaller<global::Services.GetLocationRequest> __Marshaller_GetLocationRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Services.GetLocationRequest.Parser.ParseFrom);
    static readonly Marshaller<global::DataTypes.Locations> __Marshaller_Locations = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DataTypes.Locations.Parser.ParseFrom);
    static readonly Marshaller<global::DataTypes.Location> __Marshaller_Location = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DataTypes.Location.Parser.ParseFrom);
    static readonly Marshaller<global::Services.GetVisitorRequest> __Marshaller_GetVisitorRequest = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Services.GetVisitorRequest.Parser.ParseFrom);
    static readonly Marshaller<global::DataTypes.Visitors> __Marshaller_Visitors = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DataTypes.Visitors.Parser.ParseFrom);
    static readonly Marshaller<global::DataTypes.Visitor> __Marshaller_Visitor = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::DataTypes.Visitor.Parser.ParseFrom);

    static readonly Method<global::Services.GetPersonRequest, global::DataTypes.Persons> __Method_GetPerson = new Method<global::Services.GetPersonRequest, global::DataTypes.Persons>(
        MethodType.Unary,
        __ServiceName,
        "GetPerson",
        __Marshaller_GetPersonRequest,
        __Marshaller_Persons);

    static readonly Method<global::DataTypes.Person, global::DataTypes.Person> __Method_InsertPerson = new Method<global::DataTypes.Person, global::DataTypes.Person>(
        MethodType.Unary,
        __ServiceName,
        "InsertPerson",
        __Marshaller_Person,
        __Marshaller_Person);

    static readonly Method<global::DataTypes.Person, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdatePerson = new Method<global::DataTypes.Person, global::Google.Protobuf.WellKnownTypes.Empty>(
        MethodType.Unary,
        __ServiceName,
        "UpdatePerson",
        __Marshaller_Person,
        __Marshaller_Empty);

    static readonly Method<global::DataTypes.Person, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeletePerson = new Method<global::DataTypes.Person, global::Google.Protobuf.WellKnownTypes.Empty>(
        MethodType.Unary,
        __ServiceName,
        "DeletePerson",
        __Marshaller_Person,
        __Marshaller_Empty);

    static readonly Method<global::DataTypes.Card, global::DataTypes.Card> __Method_InsertCard = new Method<global::DataTypes.Card, global::DataTypes.Card>(
        MethodType.Unary,
        __ServiceName,
        "InsertCard",
        __Marshaller_Card,
        __Marshaller_Card);

    static readonly Method<global::DataTypes.Card, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateCard = new Method<global::DataTypes.Card, global::Google.Protobuf.WellKnownTypes.Empty>(
        MethodType.Unary,
        __ServiceName,
        "UpdateCard",
        __Marshaller_Card,
        __Marshaller_Empty);

    static readonly Method<global::DataTypes.Card, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteCard = new Method<global::DataTypes.Card, global::Google.Protobuf.WellKnownTypes.Empty>(
        MethodType.Unary,
        __ServiceName,
        "DeleteCard",
        __Marshaller_Card,
        __Marshaller_Empty);

    static readonly Method<global::Services.GetLocationRequest, global::DataTypes.Locations> __Method_GetLocation = new Method<global::Services.GetLocationRequest, global::DataTypes.Locations>(
        MethodType.Unary,
        __ServiceName,
        "GetLocation",
        __Marshaller_GetLocationRequest,
        __Marshaller_Locations);

    static readonly Method<global::DataTypes.Location, global::DataTypes.Location> __Method_InsertLocation = new Method<global::DataTypes.Location, global::DataTypes.Location>(
        MethodType.Unary,
        __ServiceName,
        "InsertLocation",
        __Marshaller_Location,
        __Marshaller_Location);

    static readonly Method<global::DataTypes.Location, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateLocation = new Method<global::DataTypes.Location, global::Google.Protobuf.WellKnownTypes.Empty>(
        MethodType.Unary,
        __ServiceName,
        "UpdateLocation",
        __Marshaller_Location,
        __Marshaller_Empty);

    static readonly Method<global::DataTypes.Location, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteLocation = new Method<global::DataTypes.Location, global::Google.Protobuf.WellKnownTypes.Empty>(
        MethodType.Unary,
        __ServiceName,
        "DeleteLocation",
        __Marshaller_Location,
        __Marshaller_Empty);

    static readonly Method<global::Services.GetVisitorRequest, global::DataTypes.Visitors> __Method_GetVisitor = new Method<global::Services.GetVisitorRequest, global::DataTypes.Visitors>(
        MethodType.Unary,
        __ServiceName,
        "GetVisitor",
        __Marshaller_GetVisitorRequest,
        __Marshaller_Visitors);

    static readonly Method<global::DataTypes.Visitor, global::DataTypes.Visitor> __Method_InsertVisitor = new Method<global::DataTypes.Visitor, global::DataTypes.Visitor>(
        MethodType.Unary,
        __ServiceName,
        "InsertVisitor",
        __Marshaller_Visitor,
        __Marshaller_Visitor);

    static readonly Method<global::DataTypes.Visitor, global::Google.Protobuf.WellKnownTypes.Empty> __Method_UpdateVisitor = new Method<global::DataTypes.Visitor, global::Google.Protobuf.WellKnownTypes.Empty>(
        MethodType.Unary,
        __ServiceName,
        "UpdateVisitor",
        __Marshaller_Visitor,
        __Marshaller_Empty);

    static readonly Method<global::DataTypes.Visitor, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteVisitor = new Method<global::DataTypes.Visitor, global::Google.Protobuf.WellKnownTypes.Empty>(
        MethodType.Unary,
        __ServiceName,
        "DeleteVisitor",
        __Marshaller_Visitor,
        __Marshaller_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Services.DatabaseServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DatabaseSevice</summary>
    public abstract class DatabaseSeviceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::DataTypes.Persons> GetPerson(global::Services.GetPersonRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::DataTypes.Person> InsertPerson(global::DataTypes.Person request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> UpdatePerson(global::DataTypes.Person request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeletePerson(global::DataTypes.Person request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// rpc GetCard         ( Query               ) returns ( DataTypes.Cards        ) {}
      /// </summary>
      public virtual global::System.Threading.Tasks.Task<global::DataTypes.Card> InsertCard(global::DataTypes.Card request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> UpdateCard(global::DataTypes.Card request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteCard(global::DataTypes.Card request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::DataTypes.Locations> GetLocation(global::Services.GetLocationRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::DataTypes.Location> InsertLocation(global::DataTypes.Location request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> UpdateLocation(global::DataTypes.Location request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteLocation(global::DataTypes.Location request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::DataTypes.Visitors> GetVisitor(global::Services.GetVisitorRequest request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::DataTypes.Visitor> InsertVisitor(global::DataTypes.Visitor request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> UpdateVisitor(global::DataTypes.Visitor request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteVisitor(global::DataTypes.Visitor request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DatabaseSevice</summary>
    public class DatabaseSeviceClient : ClientBase<DatabaseSeviceClient>
    {
      /// <summary>Creates a new client for DatabaseSevice</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public DatabaseSeviceClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DatabaseSevice that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public DatabaseSeviceClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected DatabaseSeviceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected DatabaseSeviceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::DataTypes.Persons GetPerson(global::Services.GetPersonRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetPerson(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DataTypes.Persons GetPerson(global::Services.GetPersonRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetPerson, null, options, request);
      }
      public virtual AsyncUnaryCall<global::DataTypes.Persons> GetPersonAsync(global::Services.GetPersonRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetPersonAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::DataTypes.Persons> GetPersonAsync(global::Services.GetPersonRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetPerson, null, options, request);
      }
      public virtual global::DataTypes.Person InsertPerson(global::DataTypes.Person request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return InsertPerson(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DataTypes.Person InsertPerson(global::DataTypes.Person request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertPerson, null, options, request);
      }
      public virtual AsyncUnaryCall<global::DataTypes.Person> InsertPersonAsync(global::DataTypes.Person request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return InsertPersonAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::DataTypes.Person> InsertPersonAsync(global::DataTypes.Person request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertPerson, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdatePerson(global::DataTypes.Person request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdatePerson(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdatePerson(global::DataTypes.Person request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdatePerson, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdatePersonAsync(global::DataTypes.Person request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdatePersonAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdatePersonAsync(global::DataTypes.Person request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdatePerson, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeletePerson(global::DataTypes.Person request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeletePerson(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeletePerson(global::DataTypes.Person request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeletePerson, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeletePersonAsync(global::DataTypes.Person request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeletePersonAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeletePersonAsync(global::DataTypes.Person request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeletePerson, null, options, request);
      }
      /// <summary>
      /// rpc GetCard         ( Query               ) returns ( DataTypes.Cards        ) {}
      /// </summary>
      public virtual global::DataTypes.Card InsertCard(global::DataTypes.Card request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return InsertCard(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// rpc GetCard         ( Query               ) returns ( DataTypes.Cards        ) {}
      /// </summary>
      public virtual global::DataTypes.Card InsertCard(global::DataTypes.Card request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertCard, null, options, request);
      }
      /// <summary>
      /// rpc GetCard         ( Query               ) returns ( DataTypes.Cards        ) {}
      /// </summary>
      public virtual AsyncUnaryCall<global::DataTypes.Card> InsertCardAsync(global::DataTypes.Card request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return InsertCardAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// rpc GetCard         ( Query               ) returns ( DataTypes.Cards        ) {}
      /// </summary>
      public virtual AsyncUnaryCall<global::DataTypes.Card> InsertCardAsync(global::DataTypes.Card request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertCard, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateCard(global::DataTypes.Card request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateCard(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateCard(global::DataTypes.Card request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateCard, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateCardAsync(global::DataTypes.Card request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateCardAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateCardAsync(global::DataTypes.Card request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateCard, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteCard(global::DataTypes.Card request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteCard(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteCard(global::DataTypes.Card request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteCard, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteCardAsync(global::DataTypes.Card request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteCardAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteCardAsync(global::DataTypes.Card request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteCard, null, options, request);
      }
      public virtual global::DataTypes.Locations GetLocation(global::Services.GetLocationRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetLocation(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DataTypes.Locations GetLocation(global::Services.GetLocationRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetLocation, null, options, request);
      }
      public virtual AsyncUnaryCall<global::DataTypes.Locations> GetLocationAsync(global::Services.GetLocationRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetLocationAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::DataTypes.Locations> GetLocationAsync(global::Services.GetLocationRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetLocation, null, options, request);
      }
      public virtual global::DataTypes.Location InsertLocation(global::DataTypes.Location request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return InsertLocation(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DataTypes.Location InsertLocation(global::DataTypes.Location request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertLocation, null, options, request);
      }
      public virtual AsyncUnaryCall<global::DataTypes.Location> InsertLocationAsync(global::DataTypes.Location request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return InsertLocationAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::DataTypes.Location> InsertLocationAsync(global::DataTypes.Location request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertLocation, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateLocation(global::DataTypes.Location request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateLocation(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateLocation(global::DataTypes.Location request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateLocation, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateLocationAsync(global::DataTypes.Location request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateLocationAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateLocationAsync(global::DataTypes.Location request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateLocation, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteLocation(global::DataTypes.Location request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteLocation(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteLocation(global::DataTypes.Location request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteLocation, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteLocationAsync(global::DataTypes.Location request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteLocationAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteLocationAsync(global::DataTypes.Location request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteLocation, null, options, request);
      }
      public virtual global::DataTypes.Visitors GetVisitor(global::Services.GetVisitorRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetVisitor(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DataTypes.Visitors GetVisitor(global::Services.GetVisitorRequest request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetVisitor, null, options, request);
      }
      public virtual AsyncUnaryCall<global::DataTypes.Visitors> GetVisitorAsync(global::Services.GetVisitorRequest request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetVisitorAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::DataTypes.Visitors> GetVisitorAsync(global::Services.GetVisitorRequest request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetVisitor, null, options, request);
      }
      public virtual global::DataTypes.Visitor InsertVisitor(global::DataTypes.Visitor request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return InsertVisitor(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::DataTypes.Visitor InsertVisitor(global::DataTypes.Visitor request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InsertVisitor, null, options, request);
      }
      public virtual AsyncUnaryCall<global::DataTypes.Visitor> InsertVisitorAsync(global::DataTypes.Visitor request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return InsertVisitorAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::DataTypes.Visitor> InsertVisitorAsync(global::DataTypes.Visitor request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InsertVisitor, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateVisitor(global::DataTypes.Visitor request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateVisitor(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty UpdateVisitor(global::DataTypes.Visitor request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateVisitor, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateVisitorAsync(global::DataTypes.Visitor request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UpdateVisitorAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> UpdateVisitorAsync(global::DataTypes.Visitor request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateVisitor, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteVisitor(global::DataTypes.Visitor request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteVisitor(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteVisitor(global::DataTypes.Visitor request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteVisitor, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteVisitorAsync(global::DataTypes.Visitor request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return DeleteVisitorAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteVisitorAsync(global::DataTypes.Visitor request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteVisitor, null, options, request);
      }
      protected override DatabaseSeviceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DatabaseSeviceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(DatabaseSeviceBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetPerson, serviceImpl.GetPerson)
          .AddMethod(__Method_InsertPerson, serviceImpl.InsertPerson)
          .AddMethod(__Method_UpdatePerson, serviceImpl.UpdatePerson)
          .AddMethod(__Method_DeletePerson, serviceImpl.DeletePerson)
          .AddMethod(__Method_InsertCard, serviceImpl.InsertCard)
          .AddMethod(__Method_UpdateCard, serviceImpl.UpdateCard)
          .AddMethod(__Method_DeleteCard, serviceImpl.DeleteCard)
          .AddMethod(__Method_GetLocation, serviceImpl.GetLocation)
          .AddMethod(__Method_InsertLocation, serviceImpl.InsertLocation)
          .AddMethod(__Method_UpdateLocation, serviceImpl.UpdateLocation)
          .AddMethod(__Method_DeleteLocation, serviceImpl.DeleteLocation)
          .AddMethod(__Method_GetVisitor, serviceImpl.GetVisitor)
          .AddMethod(__Method_InsertVisitor, serviceImpl.InsertVisitor)
          .AddMethod(__Method_UpdateVisitor, serviceImpl.UpdateVisitor)
          .AddMethod(__Method_DeleteVisitor, serviceImpl.DeleteVisitor).Build();
    }

  }
}
#endregion
