// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/database_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Services {

  /// <summary>Holder for reflection information generated from services/database_service.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class DatabaseServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for services/database_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DatabaseServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9zZXJ2aWNlcy9kYXRhYmFzZV9zZXJ2aWNlLnByb3RvEghTZXJ2aWNlcxoU",
            "ZGF0YXR5cGVzL2RhdGEucHJvdG8yigEKD0RhdGFiYXNlU2VydmljZRI5CgNH",
            "ZXQSFy5EYXRhVHlwZXMuTWVzc2FnZUJ5dGVzGhcuRGF0YVR5cGVzLk1lc3Nh",
            "Z2VCeXRlcyIAEjwKBkNvbW1pdBIXLkRhdGFUeXBlcy5NZXNzYWdlQnl0ZXMa",
            "Fy5EYXRhVHlwZXMuTWVzc2FnZUJ5dGVzIgBCUwoHZXguZ3JwY1pCZ2l0aHVi",
            "LmNvbS9FbmVicmEvU2VydmljZUNvb3JkaW5hdG9yL2dycGMvc2VydmljZXMv",
            "ZGF0YWJhc2VzZXJ2aWNlogIDUlRHYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DataTypes.DataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
