// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/database_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Services {

  /// <summary>Holder for reflection information generated from services/database_service.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class DatabaseServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for services/database_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DatabaseServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9zZXJ2aWNlcy9kYXRhYmFzZV9zZXJ2aWNlLnByb3RvEghTZXJ2aWNlcxob",
            "Z29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvGhZkYXRhdHlwZXMvcGVyc29u",
            "LnByb3RvGhRkYXRhdHlwZXMvY2FyZC5wcm90bxoVZGF0YXR5cGVzL3Bob3Rv",
            "LnByb3RvGhhkYXRhdHlwZXMvbG9jYXRpb24ucHJvdG8aHGRhdGF0eXBlcy92",
            "aXNpdF9yZWNvcmQucHJvdG8aFGRhdGF0eXBlcy91bml0LnByb3RvGhZzZXJ2",
            "aWNlcy9xdWVyaWVzLnByb3RvMrwJCg5EYXRhYmFzZVNldmljZRI9CglHZXRQ",
            "ZXJzb24SGi5TZXJ2aWNlcy5HZXRQZXJzb25SZXF1ZXN0GhIuRGF0YVR5cGVz",
            "LlBlcnNvbnMiABI2CgxJbnNlcnRQZXJzb24SES5EYXRhVHlwZXMuUGVyc29u",
            "GhEuRGF0YVR5cGVzLlBlcnNvbiIAEjsKDFVwZGF0ZVBlcnNvbhIRLkRhdGFU",
            "eXBlcy5QZXJzb24aFi5nb29nbGUucHJvdG9idWYuRW1wdHkiABI7CgxEZWxl",
            "dGVQZXJzb24SES5EYXRhVHlwZXMuUGVyc29uGhYuZ29vZ2xlLnByb3RvYnVm",
            "LkVtcHR5IgASNwoHR2V0Q2FyZBIYLlNlcnZpY2VzLkdldENhcmRSZXF1ZXN0",
            "GhAuRGF0YVR5cGVzLkNhcmRzIgASMAoKSW5zZXJ0Q2FyZBIPLkRhdGFUeXBl",
            "cy5DYXJkGg8uRGF0YVR5cGVzLkNhcmQiABI3CgpVcGRhdGVDYXJkEg8uRGF0",
            "YVR5cGVzLkNhcmQaFi5nb29nbGUucHJvdG9idWYuRW1wdHkiABI3CgpEZWxl",
            "dGVDYXJkEg8uRGF0YVR5cGVzLkNhcmQaFi5nb29nbGUucHJvdG9idWYuRW1w",
            "dHkiABJDCgtHZXRMb2NhdGlvbhIcLlNlcnZpY2VzLkdldExvY2F0aW9uUmVx",
            "dWVzdBoULkRhdGFUeXBlcy5Mb2NhdGlvbnMiABI8Cg5JbnNlcnRMb2NhdGlv",
            "bhITLkRhdGFUeXBlcy5Mb2NhdGlvbhoTLkRhdGFUeXBlcy5Mb2NhdGlvbiIA",
            "Ej8KDlVwZGF0ZUxvY2F0aW9uEhMuRGF0YVR5cGVzLkxvY2F0aW9uGhYuZ29v",
            "Z2xlLnByb3RvYnVmLkVtcHR5IgASPwoORGVsZXRlTG9jYXRpb24SEy5EYXRh",
            "VHlwZXMuTG9jYXRpb24aFi5nb29nbGUucHJvdG9idWYuRW1wdHkiABJNCg9H",
            "ZXRWaXNpdFJlY29yZHMSHy5TZXJ2aWNlcy5HZXRWaXNpdFJlY29yZFJlcXVl",
            "c3QaFy5EYXRhVHlwZXMuVmlzaXRSZWNvcmRzIgASRQoRSW5zZXJ0VmlzaXRS",
            "ZWNvcmQSFi5EYXRhVHlwZXMuVmlzaXRSZWNvcmQaFi5EYXRhVHlwZXMuVmlz",
            "aXRSZWNvcmQiABJFChFVcGRhdGVWaXNpdFJlY29yZBIWLkRhdGFUeXBlcy5W",
            "aXNpdFJlY29yZBoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAEkUKEURlbGV0",
            "ZVZpc2l0UmVjb3JkEhYuRGF0YVR5cGVzLlZpc2l0UmVjb3JkGhYuZ29vZ2xl",
            "LnByb3RvYnVmLkVtcHR5IgASMwoLSW5zZXJ0UGhvdG8SEC5EYXRhVHlwZXMu",
            "UGhvdG8aEC5EYXRhVHlwZXMuUGhvdG8iABI5CgtEZWxldGVQaG90bxIQLkRh",
            "dGFUeXBlcy5QaG90bxoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAEkMKCUdl",
            "dENvbmZpZxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRocLkRhdGFUeXBlcy5V",
            "bml0Q29uZmlndXJhdGlvbiIAQg8KB2V4LmdycGOiAgNSVEdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::DataTypes.PersonReflection.Descriptor, global::DataTypes.CardReflection.Descriptor, global::DataTypes.PhotoReflection.Descriptor, global::DataTypes.LocationReflection.Descriptor, global::DataTypes.VisitRecordReflection.Descriptor, global::DataTypes.UnitReflection.Descriptor, global::Services.QueriesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
