// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datatypes/devices.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DataTypes {

  /// <summary>Holder for reflection information generated from datatypes/devices.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class DevicesReflection {

    #region Descriptor
    /// <summary>File descriptor for datatypes/devices.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DevicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdkYXRhdHlwZXMvZGV2aWNlcy5wcm90bxIJRGF0YVR5cGVzGhNkYXRhdHlw",
            "ZXMva2V5LnByb3RvIjMKDEFjY2Vzc0RldmljZRIMCgRuYW1lGAEgASgJEhUK",
            "DXNlcmlhbF9udW1iZXIYAiABKAYieAoMRGV2aWNlVXBkYXRlEiMKBWl0ZW1z",
            "GAEgASgLMhIuRGF0YVR5cGVzLkRldmljZXNIABI5ChBkZXZpY2Vfc3RhdGVf",
            "bXNnGAIgASgLMh0uRGF0YVR5cGVzLkRldmljZVN0YXRlTWVzc2FnZUgAQggK",
            "BnVwZGF0ZSJSCgdEZXZpY2VzEiMKC2xvY2F0aW9uX2lkGAEgASgLMg4uRGF0",
            "YVR5cGVzLktleRIiCgdkZXZpY2VzGAIgAygLMhEuRGF0YVR5cGVzLkRldmlj",
            "ZSJJCgZEZXZpY2USKgoLZGV2aWNlX3R5cGUYASABKA4yFS5EYXRhVHlwZXMu",
            "RGV2aWNlVHlwZRITCgtkZXZpY2VfbmFtZRgCIAEoCSKlAQoSRGV2aWNlU3Rh",
            "dGVNZXNzYWdlEkQKGGdlbmVyaWNfZGV2aWNlX3N0YXRlX21zZxgBIAEoCzIg",
            "LkRhdGFUeXBlcy5HZW5lcmljRGV2aWNlU3RhdGVNc2dIABJCChdhY2Nlc3Nf",
            "ZGV2aWNlX3N0YXRlX21zZxgCIAEoCzIfLkRhdGFUeXBlcy5BY2Nlc3NEZXZp",
            "Y2VTdGF0ZU1zZ0gAQgUKA21zZyKZAQoVR2VuZXJpY0RldmljZVN0YXRlTXNn",
            "EiMKC2xvY2F0aW9uX2lkGAEgASgLMg4uRGF0YVR5cGVzLktleRIjCgR0eXBl",
            "GAIgASgOMhUuRGF0YVR5cGVzLkRldmljZVR5cGUSJQoFc3RhdGUYAyABKA4y",
            "Fi5EYXRhVHlwZXMuRGV2aWNlU3RhdGUSDwoHbWVzc2FnZRgEIAEoCSJLChRB",
            "Y2Nlc3NEZXZpY2VTdGF0ZU1zZxIjCgtsb2NhdGlvbl9pZBgBIAEoCzIOLkRh",
            "dGFUeXBlcy5LZXkSDgoGb3BlbmVkGAIgASgIIhsKB0NhcmRNc2cSEAoIY2Fy",
            "ZF9udW0YASABKAkiJwoIQ2hlY2tNc2cSCgoCb2sYASABKAgSDwoHbWVzc2Fn",
            "ZRgCIAEoCSo4CgpEZXZpY2VUeXBlEg0KCU5vbmVfVHlwZRAAEg4KCkNhcmRS",
            "ZWFkZXIQARILCgdDYXB0dXJlEAIqYAoLRGV2aWNlU3RhdGUSDgoKTm9uZV9T",
            "dGF0ZRAAEgoKBkFjdGl2ZRABEhEKDVN0b3BwZWRCeVVzZXIQAhIKCgZQYXVz",
            "ZWQQAxILCgdTdG9wcGVkEAQSCQoFRXJyb3IQBUJMCgdleC5ncnBjWjtnaXRo",
            "dWIuY29tL0VuZWJyYS9TZXJ2aWNlQ29vcmRpbmF0b3IvZ3JwYy9kYXRhdHlw",
            "ZXMvZGV2aWNlc6ICA1JUR2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DataTypes.KeyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DataTypes.DeviceType), typeof(global::DataTypes.DeviceState), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DataTypes.AccessDevice), global::DataTypes.AccessDevice.Parser, new[]{ "Name", "SerialNumber" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DataTypes.DeviceUpdate), global::DataTypes.DeviceUpdate.Parser, new[]{ "Items", "DeviceStateMsg" }, new[]{ "Update" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DataTypes.Devices), global::DataTypes.Devices.Parser, new[]{ "LocationId", "Devices_" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DataTypes.Device), global::DataTypes.Device.Parser, new[]{ "DeviceType", "DeviceName" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DataTypes.DeviceStateMessage), global::DataTypes.DeviceStateMessage.Parser, new[]{ "GenericDeviceStateMsg", "AccessDeviceStateMsg" }, new[]{ "Msg" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DataTypes.GenericDeviceStateMsg), global::DataTypes.GenericDeviceStateMsg.Parser, new[]{ "LocationId", "Type", "State", "Message" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DataTypes.AccessDeviceStateMsg), global::DataTypes.AccessDeviceStateMsg.Parser, new[]{ "LocationId", "Opened" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DataTypes.CardMsg), global::DataTypes.CardMsg.Parser, new[]{ "CardNum" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DataTypes.CheckMsg), global::DataTypes.CheckMsg.Parser, new[]{ "Ok", "Message" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum DeviceType {
    [pbr::OriginalName("None_Type")] NoneType = 0,
    [pbr::OriginalName("CardReader")] CardReader = 1,
    [pbr::OriginalName("Capture")] Capture = 2,
  }

  public enum DeviceState {
    [pbr::OriginalName("None_State")] NoneState = 0,
    [pbr::OriginalName("Active")] Active = 1,
    [pbr::OriginalName("StoppedByUser")] StoppedByUser = 2,
    [pbr::OriginalName("Paused")] Paused = 3,
    [pbr::OriginalName("Stopped")] Stopped = 4,
    [pbr::OriginalName("Error")] Error = 5,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class AccessDevice : pb::IMessage<AccessDevice> {
    private static readonly pb::MessageParser<AccessDevice> _parser = new pb::MessageParser<AccessDevice>(() => new AccessDevice());
    public static pb::MessageParser<AccessDevice> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataTypes.DevicesReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public AccessDevice() {
      OnConstruction();
    }

    partial void OnConstruction();

    public AccessDevice(AccessDevice other) : this() {
      name_ = other.name_;
      serialNumber_ = other.serialNumber_;
    }

    public AccessDevice Clone() {
      return new AccessDevice(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "serial_number" field.</summary>
    public const int SerialNumberFieldNumber = 2;
    private ulong serialNumber_;
    public ulong SerialNumber {
      get { return serialNumber_; }
      set {
        serialNumber_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as AccessDevice);
    }

    public bool Equals(AccessDevice other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (SerialNumber != other.SerialNumber) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (SerialNumber != 0UL) hash ^= SerialNumber.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (SerialNumber != 0UL) {
        output.WriteRawTag(17);
        output.WriteFixed64(SerialNumber);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (SerialNumber != 0UL) {
        size += 1 + 8;
      }
      return size;
    }

    public void MergeFrom(AccessDevice other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.SerialNumber != 0UL) {
        SerialNumber = other.SerialNumber;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 17: {
            SerialNumber = input.ReadFixed64();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class DeviceUpdate : pb::IMessage<DeviceUpdate> {
    private static readonly pb::MessageParser<DeviceUpdate> _parser = new pb::MessageParser<DeviceUpdate>(() => new DeviceUpdate());
    public static pb::MessageParser<DeviceUpdate> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataTypes.DevicesReflection.Descriptor.MessageTypes[1]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public DeviceUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    public DeviceUpdate(DeviceUpdate other) : this() {
      switch (other.UpdateCase) {
        case UpdateOneofCase.Items:
          Items = other.Items.Clone();
          break;
        case UpdateOneofCase.DeviceStateMsg:
          DeviceStateMsg = other.DeviceStateMsg.Clone();
          break;
      }

    }

    public DeviceUpdate Clone() {
      return new DeviceUpdate(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    public global::DataTypes.Devices Items {
      get { return updateCase_ == UpdateOneofCase.Items ? (global::DataTypes.Devices) update_ : null; }
      set {
        update_ = value;
        updateCase_ = value == null ? UpdateOneofCase.None : UpdateOneofCase.Items;
      }
    }

    /// <summary>Field number for the "device_state_msg" field.</summary>
    public const int DeviceStateMsgFieldNumber = 2;
    /// <summary>
    ///  On location 
    /// </summary>
    public global::DataTypes.DeviceStateMessage DeviceStateMsg {
      get { return updateCase_ == UpdateOneofCase.DeviceStateMsg ? (global::DataTypes.DeviceStateMessage) update_ : null; }
      set {
        update_ = value;
        updateCase_ = value == null ? UpdateOneofCase.None : UpdateOneofCase.DeviceStateMsg;
      }
    }

    private object update_;
    /// <summary>Enum of possible cases for the "update" oneof.</summary>
    public enum UpdateOneofCase {
      None = 0,
      Items = 1,
      DeviceStateMsg = 2,
    }
    private UpdateOneofCase updateCase_ = UpdateOneofCase.None;
    public UpdateOneofCase UpdateCase {
      get { return updateCase_; }
    }

    public void ClearUpdate() {
      updateCase_ = UpdateOneofCase.None;
      update_ = null;
    }

    public override bool Equals(object other) {
      return Equals(other as DeviceUpdate);
    }

    public bool Equals(DeviceUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Items, other.Items)) return false;
      if (!object.Equals(DeviceStateMsg, other.DeviceStateMsg)) return false;
      if (UpdateCase != other.UpdateCase) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (updateCase_ == UpdateOneofCase.Items) hash ^= Items.GetHashCode();
      if (updateCase_ == UpdateOneofCase.DeviceStateMsg) hash ^= DeviceStateMsg.GetHashCode();
      hash ^= (int) updateCase_;
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (updateCase_ == UpdateOneofCase.Items) {
        output.WriteRawTag(10);
        output.WriteMessage(Items);
      }
      if (updateCase_ == UpdateOneofCase.DeviceStateMsg) {
        output.WriteRawTag(18);
        output.WriteMessage(DeviceStateMsg);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (updateCase_ == UpdateOneofCase.Items) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Items);
      }
      if (updateCase_ == UpdateOneofCase.DeviceStateMsg) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeviceStateMsg);
      }
      return size;
    }

    public void MergeFrom(DeviceUpdate other) {
      if (other == null) {
        return;
      }
      switch (other.UpdateCase) {
        case UpdateOneofCase.Items:
          Items = other.Items;
          break;
        case UpdateOneofCase.DeviceStateMsg:
          DeviceStateMsg = other.DeviceStateMsg;
          break;
      }

    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            global::DataTypes.Devices subBuilder = new global::DataTypes.Devices();
            if (updateCase_ == UpdateOneofCase.Items) {
              subBuilder.MergeFrom(Items);
            }
            input.ReadMessage(subBuilder);
            Items = subBuilder;
            break;
          }
          case 18: {
            global::DataTypes.DeviceStateMessage subBuilder = new global::DataTypes.DeviceStateMessage();
            if (updateCase_ == UpdateOneofCase.DeviceStateMsg) {
              subBuilder.MergeFrom(DeviceStateMsg);
            }
            input.ReadMessage(subBuilder);
            DeviceStateMsg = subBuilder;
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Devices : pb::IMessage<Devices> {
    private static readonly pb::MessageParser<Devices> _parser = new pb::MessageParser<Devices>(() => new Devices());
    public static pb::MessageParser<Devices> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataTypes.DevicesReflection.Descriptor.MessageTypes[2]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Devices() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Devices(Devices other) : this() {
      LocationId = other.locationId_ != null ? other.LocationId.Clone() : null;
      devices_ = other.devices_.Clone();
    }

    public Devices Clone() {
      return new Devices(this);
    }

    /// <summary>Field number for the "location_id" field.</summary>
    public const int LocationIdFieldNumber = 1;
    private global::DataTypes.Key locationId_;
    public global::DataTypes.Key LocationId {
      get { return locationId_; }
      set {
        locationId_ = value;
      }
    }

    /// <summary>Field number for the "devices" field.</summary>
    public const int Devices_FieldNumber = 2;
    private static readonly pb::FieldCodec<global::DataTypes.Device> _repeated_devices_codec
        = pb::FieldCodec.ForMessage(18, global::DataTypes.Device.Parser);
    private readonly pbc::RepeatedField<global::DataTypes.Device> devices_ = new pbc::RepeatedField<global::DataTypes.Device>();
    public pbc::RepeatedField<global::DataTypes.Device> Devices_ {
      get { return devices_; }
    }

    public override bool Equals(object other) {
      return Equals(other as Devices);
    }

    public bool Equals(Devices other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(LocationId, other.LocationId)) return false;
      if(!devices_.Equals(other.devices_)) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (locationId_ != null) hash ^= LocationId.GetHashCode();
      hash ^= devices_.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (locationId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(LocationId);
      }
      devices_.WriteTo(output, _repeated_devices_codec);
    }

    public int CalculateSize() {
      int size = 0;
      if (locationId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocationId);
      }
      size += devices_.CalculateSize(_repeated_devices_codec);
      return size;
    }

    public void MergeFrom(Devices other) {
      if (other == null) {
        return;
      }
      if (other.locationId_ != null) {
        if (locationId_ == null) {
          locationId_ = new global::DataTypes.Key();
        }
        LocationId.MergeFrom(other.LocationId);
      }
      devices_.Add(other.devices_);
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (locationId_ == null) {
              locationId_ = new global::DataTypes.Key();
            }
            input.ReadMessage(locationId_);
            break;
          }
          case 18: {
            devices_.AddEntriesFrom(input, _repeated_devices_codec);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Device : pb::IMessage<Device> {
    private static readonly pb::MessageParser<Device> _parser = new pb::MessageParser<Device>(() => new Device());
    public static pb::MessageParser<Device> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataTypes.DevicesReflection.Descriptor.MessageTypes[3]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Device() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Device(Device other) : this() {
      deviceType_ = other.deviceType_;
      deviceName_ = other.deviceName_;
    }

    public Device Clone() {
      return new Device(this);
    }

    /// <summary>Field number for the "device_type" field.</summary>
    public const int DeviceTypeFieldNumber = 1;
    private global::DataTypes.DeviceType deviceType_ = 0;
    public global::DataTypes.DeviceType DeviceType {
      get { return deviceType_; }
      set {
        deviceType_ = value;
      }
    }

    /// <summary>Field number for the "device_name" field.</summary>
    public const int DeviceNameFieldNumber = 2;
    private string deviceName_ = "";
    public string DeviceName {
      get { return deviceName_; }
      set {
        deviceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as Device);
    }

    public bool Equals(Device other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DeviceType != other.DeviceType) return false;
      if (DeviceName != other.DeviceName) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (DeviceType != 0) hash ^= DeviceType.GetHashCode();
      if (DeviceName.Length != 0) hash ^= DeviceName.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (DeviceType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) DeviceType);
      }
      if (DeviceName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DeviceName);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (DeviceType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DeviceType);
      }
      if (DeviceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceName);
      }
      return size;
    }

    public void MergeFrom(Device other) {
      if (other == null) {
        return;
      }
      if (other.DeviceType != 0) {
        DeviceType = other.DeviceType;
      }
      if (other.DeviceName.Length != 0) {
        DeviceName = other.DeviceName;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            deviceType_ = (global::DataTypes.DeviceType) input.ReadEnum();
            break;
          }
          case 18: {
            DeviceName = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// To notify about device update
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class DeviceStateMessage : pb::IMessage<DeviceStateMessage> {
    private static readonly pb::MessageParser<DeviceStateMessage> _parser = new pb::MessageParser<DeviceStateMessage>(() => new DeviceStateMessage());
    public static pb::MessageParser<DeviceStateMessage> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataTypes.DevicesReflection.Descriptor.MessageTypes[4]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public DeviceStateMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    public DeviceStateMessage(DeviceStateMessage other) : this() {
      switch (other.MsgCase) {
        case MsgOneofCase.GenericDeviceStateMsg:
          GenericDeviceStateMsg = other.GenericDeviceStateMsg.Clone();
          break;
        case MsgOneofCase.AccessDeviceStateMsg:
          AccessDeviceStateMsg = other.AccessDeviceStateMsg.Clone();
          break;
      }

    }

    public DeviceStateMessage Clone() {
      return new DeviceStateMessage(this);
    }

    /// <summary>Field number for the "generic_device_state_msg" field.</summary>
    public const int GenericDeviceStateMsgFieldNumber = 1;
    public global::DataTypes.GenericDeviceStateMsg GenericDeviceStateMsg {
      get { return msgCase_ == MsgOneofCase.GenericDeviceStateMsg ? (global::DataTypes.GenericDeviceStateMsg) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.GenericDeviceStateMsg;
      }
    }

    /// <summary>Field number for the "access_device_state_msg" field.</summary>
    public const int AccessDeviceStateMsgFieldNumber = 2;
    public global::DataTypes.AccessDeviceStateMsg AccessDeviceStateMsg {
      get { return msgCase_ == MsgOneofCase.AccessDeviceStateMsg ? (global::DataTypes.AccessDeviceStateMsg) msg_ : null; }
      set {
        msg_ = value;
        msgCase_ = value == null ? MsgOneofCase.None : MsgOneofCase.AccessDeviceStateMsg;
      }
    }

    private object msg_;
    /// <summary>Enum of possible cases for the "msg" oneof.</summary>
    public enum MsgOneofCase {
      None = 0,
      GenericDeviceStateMsg = 1,
      AccessDeviceStateMsg = 2,
    }
    private MsgOneofCase msgCase_ = MsgOneofCase.None;
    public MsgOneofCase MsgCase {
      get { return msgCase_; }
    }

    public void ClearMsg() {
      msgCase_ = MsgOneofCase.None;
      msg_ = null;
    }

    public override bool Equals(object other) {
      return Equals(other as DeviceStateMessage);
    }

    public bool Equals(DeviceStateMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(GenericDeviceStateMsg, other.GenericDeviceStateMsg)) return false;
      if (!object.Equals(AccessDeviceStateMsg, other.AccessDeviceStateMsg)) return false;
      if (MsgCase != other.MsgCase) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (msgCase_ == MsgOneofCase.GenericDeviceStateMsg) hash ^= GenericDeviceStateMsg.GetHashCode();
      if (msgCase_ == MsgOneofCase.AccessDeviceStateMsg) hash ^= AccessDeviceStateMsg.GetHashCode();
      hash ^= (int) msgCase_;
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (msgCase_ == MsgOneofCase.GenericDeviceStateMsg) {
        output.WriteRawTag(10);
        output.WriteMessage(GenericDeviceStateMsg);
      }
      if (msgCase_ == MsgOneofCase.AccessDeviceStateMsg) {
        output.WriteRawTag(18);
        output.WriteMessage(AccessDeviceStateMsg);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (msgCase_ == MsgOneofCase.GenericDeviceStateMsg) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GenericDeviceStateMsg);
      }
      if (msgCase_ == MsgOneofCase.AccessDeviceStateMsg) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AccessDeviceStateMsg);
      }
      return size;
    }

    public void MergeFrom(DeviceStateMessage other) {
      if (other == null) {
        return;
      }
      switch (other.MsgCase) {
        case MsgOneofCase.GenericDeviceStateMsg:
          GenericDeviceStateMsg = other.GenericDeviceStateMsg;
          break;
        case MsgOneofCase.AccessDeviceStateMsg:
          AccessDeviceStateMsg = other.AccessDeviceStateMsg;
          break;
      }

    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            global::DataTypes.GenericDeviceStateMsg subBuilder = new global::DataTypes.GenericDeviceStateMsg();
            if (msgCase_ == MsgOneofCase.GenericDeviceStateMsg) {
              subBuilder.MergeFrom(GenericDeviceStateMsg);
            }
            input.ReadMessage(subBuilder);
            GenericDeviceStateMsg = subBuilder;
            break;
          }
          case 18: {
            global::DataTypes.AccessDeviceStateMsg subBuilder = new global::DataTypes.AccessDeviceStateMsg();
            if (msgCase_ == MsgOneofCase.AccessDeviceStateMsg) {
              subBuilder.MergeFrom(AccessDeviceStateMsg);
            }
            input.ReadMessage(subBuilder);
            AccessDeviceStateMsg = subBuilder;
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  Other devices (binded to location)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class GenericDeviceStateMsg : pb::IMessage<GenericDeviceStateMsg> {
    private static readonly pb::MessageParser<GenericDeviceStateMsg> _parser = new pb::MessageParser<GenericDeviceStateMsg>(() => new GenericDeviceStateMsg());
    public static pb::MessageParser<GenericDeviceStateMsg> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataTypes.DevicesReflection.Descriptor.MessageTypes[5]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public GenericDeviceStateMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    public GenericDeviceStateMsg(GenericDeviceStateMsg other) : this() {
      LocationId = other.locationId_ != null ? other.LocationId.Clone() : null;
      type_ = other.type_;
      state_ = other.state_;
      message_ = other.message_;
    }

    public GenericDeviceStateMsg Clone() {
      return new GenericDeviceStateMsg(this);
    }

    /// <summary>Field number for the "location_id" field.</summary>
    public const int LocationIdFieldNumber = 1;
    private global::DataTypes.Key locationId_;
    public global::DataTypes.Key LocationId {
      get { return locationId_; }
      set {
        locationId_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::DataTypes.DeviceType type_ = 0;
    public global::DataTypes.DeviceType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 3;
    private global::DataTypes.DeviceState state_ = 0;
    public global::DataTypes.DeviceState State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 4;
    private string message_ = "";
    /// <summary>
    /// msg from device
    /// </summary>
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as GenericDeviceStateMsg);
    }

    public bool Equals(GenericDeviceStateMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(LocationId, other.LocationId)) return false;
      if (Type != other.Type) return false;
      if (State != other.State) return false;
      if (Message != other.Message) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (locationId_ != null) hash ^= LocationId.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (State != 0) hash ^= State.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (locationId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(LocationId);
      }
      if (Type != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (State != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) State);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (locationId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocationId);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (State != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(GenericDeviceStateMsg other) {
      if (other == null) {
        return;
      }
      if (other.locationId_ != null) {
        if (locationId_ == null) {
          locationId_ = new global::DataTypes.Key();
        }
        LocationId.MergeFrom(other.LocationId);
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.State != 0) {
        State = other.State;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (locationId_ == null) {
              locationId_ = new global::DataTypes.Key();
            }
            input.ReadMessage(locationId_);
            break;
          }
          case 16: {
            type_ = (global::DataTypes.DeviceType) input.ReadEnum();
            break;
          }
          case 24: {
            state_ = (global::DataTypes.DeviceState) input.ReadEnum();
            break;
          }
          case 34: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///  Notify on door state  (binded to location)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class AccessDeviceStateMsg : pb::IMessage<AccessDeviceStateMsg> {
    private static readonly pb::MessageParser<AccessDeviceStateMsg> _parser = new pb::MessageParser<AccessDeviceStateMsg>(() => new AccessDeviceStateMsg());
    public static pb::MessageParser<AccessDeviceStateMsg> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataTypes.DevicesReflection.Descriptor.MessageTypes[6]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public AccessDeviceStateMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    public AccessDeviceStateMsg(AccessDeviceStateMsg other) : this() {
      LocationId = other.locationId_ != null ? other.LocationId.Clone() : null;
      opened_ = other.opened_;
    }

    public AccessDeviceStateMsg Clone() {
      return new AccessDeviceStateMsg(this);
    }

    /// <summary>Field number for the "location_id" field.</summary>
    public const int LocationIdFieldNumber = 1;
    private global::DataTypes.Key locationId_;
    public global::DataTypes.Key LocationId {
      get { return locationId_; }
      set {
        locationId_ = value;
      }
    }

    /// <summary>Field number for the "opened" field.</summary>
    public const int OpenedFieldNumber = 2;
    private bool opened_;
    public bool Opened {
      get { return opened_; }
      set {
        opened_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as AccessDeviceStateMsg);
    }

    public bool Equals(AccessDeviceStateMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(LocationId, other.LocationId)) return false;
      if (Opened != other.Opened) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (locationId_ != null) hash ^= LocationId.GetHashCode();
      if (Opened != false) hash ^= Opened.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (locationId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(LocationId);
      }
      if (Opened != false) {
        output.WriteRawTag(16);
        output.WriteBool(Opened);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (locationId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LocationId);
      }
      if (Opened != false) {
        size += 1 + 1;
      }
      return size;
    }

    public void MergeFrom(AccessDeviceStateMsg other) {
      if (other == null) {
        return;
      }
      if (other.locationId_ != null) {
        if (locationId_ == null) {
          locationId_ = new global::DataTypes.Key();
        }
        LocationId.MergeFrom(other.LocationId);
      }
      if (other.Opened != false) {
        Opened = other.Opened;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (locationId_ == null) {
              locationId_ = new global::DataTypes.Key();
            }
            input.ReadMessage(locationId_);
            break;
          }
          case 16: {
            Opened = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class CardMsg : pb::IMessage<CardMsg> {
    private static readonly pb::MessageParser<CardMsg> _parser = new pb::MessageParser<CardMsg>(() => new CardMsg());
    public static pb::MessageParser<CardMsg> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataTypes.DevicesReflection.Descriptor.MessageTypes[7]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public CardMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    public CardMsg(CardMsg other) : this() {
      cardNum_ = other.cardNum_;
    }

    public CardMsg Clone() {
      return new CardMsg(this);
    }

    /// <summary>Field number for the "card_num" field.</summary>
    public const int CardNumFieldNumber = 1;
    private string cardNum_ = "";
    public string CardNum {
      get { return cardNum_; }
      set {
        cardNum_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as CardMsg);
    }

    public bool Equals(CardMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CardNum != other.CardNum) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (CardNum.Length != 0) hash ^= CardNum.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (CardNum.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CardNum);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (CardNum.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CardNum);
      }
      return size;
    }

    public void MergeFrom(CardMsg other) {
      if (other == null) {
        return;
      }
      if (other.CardNum.Length != 0) {
        CardNum = other.CardNum;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            CardNum = input.ReadString();
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class CheckMsg : pb::IMessage<CheckMsg> {
    private static readonly pb::MessageParser<CheckMsg> _parser = new pb::MessageParser<CheckMsg>(() => new CheckMsg());
    public static pb::MessageParser<CheckMsg> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataTypes.DevicesReflection.Descriptor.MessageTypes[8]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public CheckMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    public CheckMsg(CheckMsg other) : this() {
      ok_ = other.ok_;
      message_ = other.message_;
    }

    public CheckMsg Clone() {
      return new CheckMsg(this);
    }

    /// <summary>Field number for the "ok" field.</summary>
    public const int OkFieldNumber = 1;
    private bool ok_;
    public bool Ok {
      get { return ok_; }
      set {
        ok_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as CheckMsg);
    }

    public bool Equals(CheckMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ok != other.Ok) return false;
      if (Message != other.Message) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Ok != false) hash ^= Ok.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Ok != false) {
        output.WriteRawTag(8);
        output.WriteBool(Ok);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Ok != false) {
        size += 1 + 1;
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    public void MergeFrom(CheckMsg other) {
      if (other == null) {
        return;
      }
      if (other.Ok != false) {
        Ok = other.Ok;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Ok = input.ReadBool();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
