// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/master_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Services {

  /// <summary>Holder for reflection information generated from services/master_service.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class MasterServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for services/master_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MasterServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1zZXJ2aWNlcy9tYXN0ZXJfc2VydmljZS5wcm90bxIIU2VydmljZXMaG2dv",
            "b2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90bxoUZGF0YXR5cGVzL3VuaXQucHJv",
            "dG8aGGRhdGF0eXBlcy9sb2NhdGlvbi5wcm90bxocZGF0YXR5cGVzL3Zpc2l0",
            "X3JlY29yZC5wcm90bzKaAwoNTWFzdGVyU2VydmljZRI9CgdDb25uZWN0Ehgu",
            "RGF0YVR5cGVzLkNvbm5lY3RlZFVuaXQaFi5nb29nbGUucHJvdG9idWYuRW1w",
            "dHkiABI/CglIZWFydGJlYXQSGC5EYXRhVHlwZXMuQ29ubmVjdGVkVW5pdBoW",
            "Lmdvb2dsZS5wcm90b2J1Zi5FbXB0eSIAEj8KDVNlbmRMb2NhdGlvbnMSFC5E",
            "YXRhVHlwZXMuTG9jYXRpb25zGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IgAS",
            "QQoMU2VuZEFjdGl2aXR5EhcuRGF0YVR5cGVzLlZpc2l0UmVjb3JkcxoWLmdv",
            "b2dsZS5wcm90b2J1Zi5FbXB0eSIAEk0KE05vdGlmeUxvY2F0aW9uU3RhdGUS",
            "HC5EYXRhVHlwZXMuVW5pdExvY2F0aW9uU3RhdGUaFi5nb29nbGUucHJvdG9i",
            "dWYuRW1wdHkiABI2CghHZXRVbml0cxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0",
            "eRoQLkRhdGFUeXBlcy5Vbml0cyIAQg8KB2V4LmdycGOiAgNSVEdiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::DataTypes.UnitReflection.Descriptor, global::DataTypes.LocationReflection.Descriptor, global::DataTypes.VisitRecordReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
