// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datatypes/photo.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DataTypes {

  /// <summary>Holder for reflection information generated from datatypes/photo.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class PhotoReflection {

    #region Descriptor
    /// <summary>File descriptor for datatypes/photo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PhotoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVkYXRhdHlwZXMvcGhvdG8ucHJvdG8SCURhdGFUeXBlcxoaZGF0YXR5cGVz",
            "L2Jpb21ldHJpY3MucHJvdG8aFGRhdGF0eXBlcy9kYXRhLnByb3RvIsgBCgVQ",
            "aG90bxIaCgJpZBgBIAEoCzIOLkRhdGFUeXBlcy5LZXkSCwoDdXJsGAIgASgJ",
            "Eg0KBXdpZHRoGAMgASgFEg4KBmhlaWdodBgEIAEoBRIjCgdwdXJwb3NlGAUg",
            "ASgOMhIuRGF0YVR5cGVzLlB1cnBvc2USMAoOYmlvbWV0cmljX3R5cGUYBiAB",
            "KA4yGC5EYXRhVHlwZXMuQmlvbWV0cmljVHlwZRIgCghvd25lcl9pZBgHIAEo",
            "CzIOLkRhdGFUeXBlcy5LZXkiOQoGUGhvdG9zEiAKBnBob3RvcxgBIAMoCzIQ",
            "LkRhdGFUeXBlcy5QaG90bxINCgVjb3VudBgCIAEoAyo5CgdQdXJwb3NlEg8K",
            "C05vbmVQdXJwb3NlEAASDQoJVGh1bWJuYWlsEAESDgoKUG9wdWxhdGlvbhAC",
            "QkoKB2V4LmdycGNaOWdpdGh1Yi5jb20vRW5lYnJhL1NlcnZpY2VDb29yZGlu",
            "YXRvci9ncnBjL2RhdGF0eXBlcy9waG90b6ICA1JUR2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DataTypes.BiometricsReflection.Descriptor, global::DataTypes.DataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DataTypes.Purpose), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DataTypes.Photo), global::DataTypes.Photo.Parser, new[]{ "Id", "Url", "Width", "Height", "Purpose", "BiometricType", "OwnerId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DataTypes.Photos), global::DataTypes.Photos.Parser, new[]{ "Photos_", "Count" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Purpose {
    [pbr::OriginalName("NonePurpose")] NonePurpose = 0,
    [pbr::OriginalName("Thumbnail")] Thumbnail = 1,
    [pbr::OriginalName("Population")] Population = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Photo : pb::IMessage<Photo> {
    private static readonly pb::MessageParser<Photo> _parser = new pb::MessageParser<Photo>(() => new Photo());
    public static pb::MessageParser<Photo> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataTypes.PhotoReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Photo() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Photo(Photo other) : this() {
      Id = other.id_ != null ? other.Id.Clone() : null;
      url_ = other.url_;
      width_ = other.width_;
      height_ = other.height_;
      purpose_ = other.purpose_;
      biometricType_ = other.biometricType_;
      OwnerId = other.ownerId_ != null ? other.OwnerId.Clone() : null;
    }

    public Photo Clone() {
      return new Photo(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::DataTypes.Key id_;
    public global::DataTypes.Key Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 2;
    private string url_ = "";
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "width" field.</summary>
    public const int WidthFieldNumber = 3;
    private int width_;
    public int Width {
      get { return width_; }
      set {
        width_ = value;
      }
    }

    /// <summary>Field number for the "height" field.</summary>
    public const int HeightFieldNumber = 4;
    private int height_;
    public int Height {
      get { return height_; }
      set {
        height_ = value;
      }
    }

    /// <summary>Field number for the "purpose" field.</summary>
    public const int PurposeFieldNumber = 5;
    private global::DataTypes.Purpose purpose_ = 0;
    public global::DataTypes.Purpose Purpose {
      get { return purpose_; }
      set {
        purpose_ = value;
      }
    }

    /// <summary>Field number for the "biometric_type" field.</summary>
    public const int BiometricTypeFieldNumber = 6;
    private global::DataTypes.BiometricType biometricType_ = 0;
    public global::DataTypes.BiometricType BiometricType {
      get { return biometricType_; }
      set {
        biometricType_ = value;
      }
    }

    /// <summary>Field number for the "owner_id" field.</summary>
    public const int OwnerIdFieldNumber = 7;
    private global::DataTypes.Key ownerId_;
    public global::DataTypes.Key OwnerId {
      get { return ownerId_; }
      set {
        ownerId_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as Photo);
    }

    public bool Equals(Photo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Id, other.Id)) return false;
      if (Url != other.Url) return false;
      if (Width != other.Width) return false;
      if (Height != other.Height) return false;
      if (Purpose != other.Purpose) return false;
      if (BiometricType != other.BiometricType) return false;
      if (!object.Equals(OwnerId, other.OwnerId)) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (id_ != null) hash ^= Id.GetHashCode();
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (Width != 0) hash ^= Width.GetHashCode();
      if (Height != 0) hash ^= Height.GetHashCode();
      if (Purpose != 0) hash ^= Purpose.GetHashCode();
      if (BiometricType != 0) hash ^= BiometricType.GetHashCode();
      if (ownerId_ != null) hash ^= OwnerId.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Url);
      }
      if (Width != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Width);
      }
      if (Height != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Height);
      }
      if (Purpose != 0) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Purpose);
      }
      if (BiometricType != 0) {
        output.WriteRawTag(48);
        output.WriteEnum((int) BiometricType);
      }
      if (ownerId_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(OwnerId);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (id_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (Width != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Width);
      }
      if (Height != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Height);
      }
      if (Purpose != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Purpose);
      }
      if (BiometricType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BiometricType);
      }
      if (ownerId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OwnerId);
      }
      return size;
    }

    public void MergeFrom(Photo other) {
      if (other == null) {
        return;
      }
      if (other.id_ != null) {
        if (id_ == null) {
          id_ = new global::DataTypes.Key();
        }
        Id.MergeFrom(other.Id);
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      if (other.Width != 0) {
        Width = other.Width;
      }
      if (other.Height != 0) {
        Height = other.Height;
      }
      if (other.Purpose != 0) {
        Purpose = other.Purpose;
      }
      if (other.BiometricType != 0) {
        BiometricType = other.BiometricType;
      }
      if (other.ownerId_ != null) {
        if (ownerId_ == null) {
          ownerId_ = new global::DataTypes.Key();
        }
        OwnerId.MergeFrom(other.OwnerId);
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (id_ == null) {
              id_ = new global::DataTypes.Key();
            }
            input.ReadMessage(id_);
            break;
          }
          case 18: {
            Url = input.ReadString();
            break;
          }
          case 24: {
            Width = input.ReadInt32();
            break;
          }
          case 32: {
            Height = input.ReadInt32();
            break;
          }
          case 40: {
            purpose_ = (global::DataTypes.Purpose) input.ReadEnum();
            break;
          }
          case 48: {
            biometricType_ = (global::DataTypes.BiometricType) input.ReadEnum();
            break;
          }
          case 58: {
            if (ownerId_ == null) {
              ownerId_ = new global::DataTypes.Key();
            }
            input.ReadMessage(ownerId_);
            break;
          }
        }
      }
    }

  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Photos : pb::IMessage<Photos> {
    private static readonly pb::MessageParser<Photos> _parser = new pb::MessageParser<Photos>(() => new Photos());
    public static pb::MessageParser<Photos> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::DataTypes.PhotoReflection.Descriptor.MessageTypes[1]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public Photos() {
      OnConstruction();
    }

    partial void OnConstruction();

    public Photos(Photos other) : this() {
      photos_ = other.photos_.Clone();
      count_ = other.count_;
    }

    public Photos Clone() {
      return new Photos(this);
    }

    /// <summary>Field number for the "photos" field.</summary>
    public const int Photos_FieldNumber = 1;
    private static readonly pb::FieldCodec<global::DataTypes.Photo> _repeated_photos_codec
        = pb::FieldCodec.ForMessage(10, global::DataTypes.Photo.Parser);
    private readonly pbc::RepeatedField<global::DataTypes.Photo> photos_ = new pbc::RepeatedField<global::DataTypes.Photo>();
    public pbc::RepeatedField<global::DataTypes.Photo> Photos_ {
      get { return photos_; }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 2;
    private long count_;
    public long Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    public override bool Equals(object other) {
      return Equals(other as Photos);
    }

    public bool Equals(Photos other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!photos_.Equals(other.photos_)) return false;
      if (Count != other.Count) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      hash ^= photos_.GetHashCode();
      if (Count != 0L) hash ^= Count.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      photos_.WriteTo(output, _repeated_photos_codec);
      if (Count != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Count);
      }
    }

    public int CalculateSize() {
      int size = 0;
      size += photos_.CalculateSize(_repeated_photos_codec);
      if (Count != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Count);
      }
      return size;
    }

    public void MergeFrom(Photos other) {
      if (other == null) {
        return;
      }
      photos_.Add(other.photos_);
      if (other.Count != 0L) {
        Count = other.Count;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            photos_.AddEntriesFrom(input, _repeated_photos_codec);
            break;
          }
          case 16: {
            Count = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
