// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/database_service.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "services/database_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Services {

namespace {


}  // namespace


void protobuf_AssignDesc_services_2fdatabase_5fservice_2eproto() {
  protobuf_AddDesc_services_2fdatabase_5fservice_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "services/database_service.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_services_2fdatabase_5fservice_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_services_2fdatabase_5fservice_2eproto() {
}

void protobuf_AddDesc_services_2fdatabase_5fservice_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fempty_2eproto();
  ::DataTypes::protobuf_AddDesc_datatypes_2fperson_2eproto();
  ::DataTypes::protobuf_AddDesc_datatypes_2fcard_2eproto();
  ::DataTypes::protobuf_AddDesc_datatypes_2flocation_2eproto();
  ::DataTypes::protobuf_AddDesc_datatypes_2fvisitor_2eproto();
  ::Services::protobuf_AddDesc_services_2fqueries_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\037services/database_service.proto\022\010Servi"
    "ces\032\033google/protobuf/empty.proto\032\026dataty"
    "pes/person.proto\032\024datatypes/card.proto\032\030"
    "datatypes/location.proto\032\027datatypes/visi"
    "tor.proto\032\026services/queries.proto2\245\007\n\016Da"
    "tabaseSevice\022=\n\tGetPerson\022\032.Services.Get"
    "PersonRequest\032\022.DataTypes.Persons\"\000\0226\n\014I"
    "nsertPerson\022\021.DataTypes.Person\032\021.DataTyp"
    "es.Person\"\000\022;\n\014UpdatePerson\022\021.DataTypes."
    "Person\032\026.google.protobuf.Empty\"\000\022;\n\014Dele"
    "tePerson\022\021.DataTypes.Person\032\026.google.pro"
    "tobuf.Empty\"\000\0220\n\nInsertCard\022\017.DataTypes."
    "Card\032\017.DataTypes.Card\"\000\0227\n\nUpdateCard\022\017."
    "DataTypes.Card\032\026.google.protobuf.Empty\"\000"
    "\0227\n\nDeleteCard\022\017.DataTypes.Card\032\026.google"
    ".protobuf.Empty\"\000\022C\n\013GetLocation\022\034.Servi"
    "ces.GetLocationRequest\032\024.DataTypes.Locat"
    "ions\"\000\022<\n\016InsertLocation\022\023.DataTypes.Loc"
    "ation\032\023.DataTypes.Location\"\000\022\?\n\016UpdateLo"
    "cation\022\023.DataTypes.Location\032\026.google.pro"
    "tobuf.Empty\"\000\022\?\n\016DeleteLocation\022\023.DataTy"
    "pes.Location\032\026.google.protobuf.Empty\"\000\022@"
    "\n\nGetVisitor\022\033.Services.GetVisitorReques"
    "t\032\023.DataTypes.Visitors\"\000\0229\n\rInsertVisito"
    "r\022\022.DataTypes.Visitor\032\022.DataTypes.Visito"
    "r\"\000\022=\n\rUpdateVisitor\022\022.DataTypes.Visitor"
    "\032\026.google.protobuf.Empty\"\000\022=\n\rDeleteVisi"
    "tor\022\022.DataTypes.Visitor\032\026.google.protobu"
    "f.Empty\"\000B\017\n\007ex.grpc\242\002\003RTGb\006proto3", 1154);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "services/database_service.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_services_2fdatabase_5fservice_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_services_2fdatabase_5fservice_2eproto {
  StaticDescriptorInitializer_services_2fdatabase_5fservice_2eproto() {
    protobuf_AddDesc_services_2fdatabase_5fservice_2eproto();
  }
} static_descriptor_initializer_services_2fdatabase_5fservice_2eproto_;

// @@protoc_insertion_point(namespace_scope)

}  // namespace Services

// @@protoc_insertion_point(global_scope)
