// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datatypes/photo.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "datatypes/photo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace DataTypes {

namespace {

const ::google::protobuf::Descriptor* Photo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Photo_reflection_ = NULL;
const ::google::protobuf::Descriptor* Photos_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Photos_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Purpose_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_datatypes_2fphoto_2eproto() {
  protobuf_AddDesc_datatypes_2fphoto_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "datatypes/photo.proto");
  GOOGLE_CHECK(file != NULL);
  Photo_descriptor_ = file->message_type(0);
  static const int Photo_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Photo, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Photo, url_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Photo, width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Photo, height_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Photo, purpose_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Photo, biotype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Photo, owner_id_),
  };
  Photo_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Photo_descriptor_,
      Photo::default_instance_,
      Photo_offsets_,
      -1,
      -1,
      -1,
      sizeof(Photo),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Photo, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Photo, _is_default_instance_));
  Photos_descriptor_ = file->message_type(1);
  static const int Photos_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Photos, photos_),
  };
  Photos_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Photos_descriptor_,
      Photos::default_instance_,
      Photos_offsets_,
      -1,
      -1,
      -1,
      sizeof(Photos),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Photos, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Photos, _is_default_instance_));
  Purpose_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_datatypes_2fphoto_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Photo_descriptor_, &Photo::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Photos_descriptor_, &Photos::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_datatypes_2fphoto_2eproto() {
  delete Photo::default_instance_;
  delete Photo_reflection_;
  delete Photos::default_instance_;
  delete Photos_reflection_;
}

void protobuf_AddDesc_datatypes_2fphoto_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::DataTypes::protobuf_AddDesc_datatypes_2fbiometrics_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\025datatypes/photo.proto\022\tDataTypes\032\032data"
    "types/biometrics.proto\"\241\001\n\005Photo\022\n\n\002id\030\001"
    " \001(\003\022\013\n\003url\030\002 \001(\t\022\r\n\005width\030\003 \001(\005\022\016\n\006heig"
    "ht\030\004 \001(\005\022#\n\007purpose\030\005 \001(\0162\022.DataTypes.Pu"
    "rpose\022)\n\007biotype\030\006 \001(\0162\030.DataTypes.Biome"
    "tricType\022\020\n\010owner_id\030\007 \001(\003\"*\n\006Photos\022 \n\006"
    "photos\030\001 \003(\0132\020.DataTypes.Photo*9\n\007Purpos"
    "e\022\017\n\013NonePurpose\020\000\022\r\n\tThumbnail\020\001\022\016\n\nPop"
    "ulation\020\002B\017\n\007ex.grpc\242\002\003RTGb\006proto3", 354);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "datatypes/photo.proto", &protobuf_RegisterTypes);
  Photo::default_instance_ = new Photo();
  Photos::default_instance_ = new Photos();
  Photo::default_instance_->InitAsDefaultInstance();
  Photos::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_datatypes_2fphoto_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_datatypes_2fphoto_2eproto {
  StaticDescriptorInitializer_datatypes_2fphoto_2eproto() {
    protobuf_AddDesc_datatypes_2fphoto_2eproto();
  }
} static_descriptor_initializer_datatypes_2fphoto_2eproto_;
const ::google::protobuf::EnumDescriptor* Purpose_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Purpose_descriptor_;
}
bool Purpose_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Photo::kIdFieldNumber;
const int Photo::kUrlFieldNumber;
const int Photo::kWidthFieldNumber;
const int Photo::kHeightFieldNumber;
const int Photo::kPurposeFieldNumber;
const int Photo::kBiotypeFieldNumber;
const int Photo::kOwnerIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Photo::Photo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DataTypes.Photo)
}

void Photo::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Photo::Photo(const Photo& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DataTypes.Photo)
}

void Photo::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = GOOGLE_LONGLONG(0);
  url_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  width_ = 0;
  height_ = 0;
  purpose_ = 0;
  biotype_ = 0;
  owner_id_ = GOOGLE_LONGLONG(0);
}

Photo::~Photo() {
  // @@protoc_insertion_point(destructor:DataTypes.Photo)
  SharedDtor();
}

void Photo::SharedDtor() {
  url_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Photo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Photo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Photo_descriptor_;
}

const Photo& Photo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_datatypes_2fphoto_2eproto();
  return *default_instance_;
}

Photo* Photo::default_instance_ = NULL;

Photo* Photo::New(::google::protobuf::Arena* arena) const {
  Photo* n = new Photo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Photo::Clear() {
// @@protoc_insertion_point(message_clear_start:DataTypes.Photo)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(Photo, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<Photo*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(width_, owner_id_);
  id_ = GOOGLE_LONGLONG(0);
  url_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

}

bool Photo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DataTypes.Photo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int64 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &id_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_url;
        break;
      }

      // optional string url = 2;
      case 2: {
        if (tag == 18) {
         parse_url:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_url()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->url().data(), this->url().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DataTypes.Photo.url"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_width;
        break;
      }

      // optional int32 width = 3;
      case 3: {
        if (tag == 24) {
         parse_width:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &width_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_height;
        break;
      }

      // optional int32 height = 4;
      case 4: {
        if (tag == 32) {
         parse_height:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &height_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_purpose;
        break;
      }

      // optional .DataTypes.Purpose purpose = 5;
      case 5: {
        if (tag == 40) {
         parse_purpose:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_purpose(static_cast< ::DataTypes::Purpose >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_biotype;
        break;
      }

      // optional .DataTypes.BiometricType biotype = 6;
      case 6: {
        if (tag == 48) {
         parse_biotype:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_biotype(static_cast< ::DataTypes::BiometricType >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_owner_id;
        break;
      }

      // optional int64 owner_id = 7;
      case 7: {
        if (tag == 56) {
         parse_owner_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &owner_id_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DataTypes.Photo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DataTypes.Photo)
  return false;
#undef DO_
}

void Photo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DataTypes.Photo)
  // optional int64 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->id(), output);
  }

  // optional string url = 2;
  if (this->url().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->url().data(), this->url().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DataTypes.Photo.url");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->url(), output);
  }

  // optional int32 width = 3;
  if (this->width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->width(), output);
  }

  // optional int32 height = 4;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->height(), output);
  }

  // optional .DataTypes.Purpose purpose = 5;
  if (this->purpose() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->purpose(), output);
  }

  // optional .DataTypes.BiometricType biotype = 6;
  if (this->biotype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      6, this->biotype(), output);
  }

  // optional int64 owner_id = 7;
  if (this->owner_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(7, this->owner_id(), output);
  }

  // @@protoc_insertion_point(serialize_end:DataTypes.Photo)
}

::google::protobuf::uint8* Photo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DataTypes.Photo)
  // optional int64 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->id(), target);
  }

  // optional string url = 2;
  if (this->url().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->url().data(), this->url().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DataTypes.Photo.url");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->url(), target);
  }

  // optional int32 width = 3;
  if (this->width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->width(), target);
  }

  // optional int32 height = 4;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->height(), target);
  }

  // optional .DataTypes.Purpose purpose = 5;
  if (this->purpose() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->purpose(), target);
  }

  // optional .DataTypes.BiometricType biotype = 6;
  if (this->biotype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      6, this->biotype(), target);
  }

  // optional int64 owner_id = 7;
  if (this->owner_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(7, this->owner_id(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:DataTypes.Photo)
  return target;
}

int Photo::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:DataTypes.Photo)
  int total_size = 0;

  // optional int64 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->id());
  }

  // optional string url = 2;
  if (this->url().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->url());
  }

  // optional int32 width = 3;
  if (this->width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->width());
  }

  // optional int32 height = 4;
  if (this->height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->height());
  }

  // optional .DataTypes.Purpose purpose = 5;
  if (this->purpose() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->purpose());
  }

  // optional .DataTypes.BiometricType biotype = 6;
  if (this->biotype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->biotype());
  }

  // optional int64 owner_id = 7;
  if (this->owner_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->owner_id());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Photo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DataTypes.Photo)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Photo* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Photo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DataTypes.Photo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DataTypes.Photo)
    MergeFrom(*source);
  }
}

void Photo::MergeFrom(const Photo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DataTypes.Photo)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.url().size() > 0) {

    url_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.url_);
  }
  if (from.width() != 0) {
    set_width(from.width());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
  if (from.purpose() != 0) {
    set_purpose(from.purpose());
  }
  if (from.biotype() != 0) {
    set_biotype(from.biotype());
  }
  if (from.owner_id() != 0) {
    set_owner_id(from.owner_id());
  }
}

void Photo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DataTypes.Photo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Photo::CopyFrom(const Photo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DataTypes.Photo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Photo::IsInitialized() const {

  return true;
}

void Photo::Swap(Photo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Photo::InternalSwap(Photo* other) {
  std::swap(id_, other->id_);
  url_.Swap(&other->url_);
  std::swap(width_, other->width_);
  std::swap(height_, other->height_);
  std::swap(purpose_, other->purpose_);
  std::swap(biotype_, other->biotype_);
  std::swap(owner_id_, other->owner_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Photo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Photo_descriptor_;
  metadata.reflection = Photo_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Photo

// optional int64 id = 1;
void Photo::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 Photo::id() const {
  // @@protoc_insertion_point(field_get:DataTypes.Photo.id)
  return id_;
}
 void Photo::set_id(::google::protobuf::int64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:DataTypes.Photo.id)
}

// optional string url = 2;
void Photo::clear_url() {
  url_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Photo::url() const {
  // @@protoc_insertion_point(field_get:DataTypes.Photo.url)
  return url_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Photo::set_url(const ::std::string& value) {
  
  url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DataTypes.Photo.url)
}
 void Photo::set_url(const char* value) {
  
  url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DataTypes.Photo.url)
}
 void Photo::set_url(const char* value, size_t size) {
  
  url_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DataTypes.Photo.url)
}
 ::std::string* Photo::mutable_url() {
  
  // @@protoc_insertion_point(field_mutable:DataTypes.Photo.url)
  return url_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Photo::release_url() {
  // @@protoc_insertion_point(field_release:DataTypes.Photo.url)
  
  return url_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Photo::set_allocated_url(::std::string* url) {
  if (url != NULL) {
    
  } else {
    
  }
  url_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), url);
  // @@protoc_insertion_point(field_set_allocated:DataTypes.Photo.url)
}

// optional int32 width = 3;
void Photo::clear_width() {
  width_ = 0;
}
 ::google::protobuf::int32 Photo::width() const {
  // @@protoc_insertion_point(field_get:DataTypes.Photo.width)
  return width_;
}
 void Photo::set_width(::google::protobuf::int32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:DataTypes.Photo.width)
}

// optional int32 height = 4;
void Photo::clear_height() {
  height_ = 0;
}
 ::google::protobuf::int32 Photo::height() const {
  // @@protoc_insertion_point(field_get:DataTypes.Photo.height)
  return height_;
}
 void Photo::set_height(::google::protobuf::int32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:DataTypes.Photo.height)
}

// optional .DataTypes.Purpose purpose = 5;
void Photo::clear_purpose() {
  purpose_ = 0;
}
 ::DataTypes::Purpose Photo::purpose() const {
  // @@protoc_insertion_point(field_get:DataTypes.Photo.purpose)
  return static_cast< ::DataTypes::Purpose >(purpose_);
}
 void Photo::set_purpose(::DataTypes::Purpose value) {
  
  purpose_ = value;
  // @@protoc_insertion_point(field_set:DataTypes.Photo.purpose)
}

// optional .DataTypes.BiometricType biotype = 6;
void Photo::clear_biotype() {
  biotype_ = 0;
}
 ::DataTypes::BiometricType Photo::biotype() const {
  // @@protoc_insertion_point(field_get:DataTypes.Photo.biotype)
  return static_cast< ::DataTypes::BiometricType >(biotype_);
}
 void Photo::set_biotype(::DataTypes::BiometricType value) {
  
  biotype_ = value;
  // @@protoc_insertion_point(field_set:DataTypes.Photo.biotype)
}

// optional int64 owner_id = 7;
void Photo::clear_owner_id() {
  owner_id_ = GOOGLE_LONGLONG(0);
}
 ::google::protobuf::int64 Photo::owner_id() const {
  // @@protoc_insertion_point(field_get:DataTypes.Photo.owner_id)
  return owner_id_;
}
 void Photo::set_owner_id(::google::protobuf::int64 value) {
  
  owner_id_ = value;
  // @@protoc_insertion_point(field_set:DataTypes.Photo.owner_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Photos::kPhotosFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Photos::Photos()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DataTypes.Photos)
}

void Photos::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Photos::Photos(const Photos& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DataTypes.Photos)
}

void Photos::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

Photos::~Photos() {
  // @@protoc_insertion_point(destructor:DataTypes.Photos)
  SharedDtor();
}

void Photos::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Photos::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Photos::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Photos_descriptor_;
}

const Photos& Photos::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_datatypes_2fphoto_2eproto();
  return *default_instance_;
}

Photos* Photos::default_instance_ = NULL;

Photos* Photos::New(::google::protobuf::Arena* arena) const {
  Photos* n = new Photos;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Photos::Clear() {
// @@protoc_insertion_point(message_clear_start:DataTypes.Photos)
  photos_.Clear();
}

bool Photos::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DataTypes.Photos)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .DataTypes.Photo photos = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_photos:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_photos()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_photos;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DataTypes.Photos)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DataTypes.Photos)
  return false;
#undef DO_
}

void Photos::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DataTypes.Photos)
  // repeated .DataTypes.Photo photos = 1;
  for (unsigned int i = 0, n = this->photos_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->photos(i), output);
  }

  // @@protoc_insertion_point(serialize_end:DataTypes.Photos)
}

::google::protobuf::uint8* Photos::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DataTypes.Photos)
  // repeated .DataTypes.Photo photos = 1;
  for (unsigned int i = 0, n = this->photos_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->photos(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:DataTypes.Photos)
  return target;
}

int Photos::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:DataTypes.Photos)
  int total_size = 0;

  // repeated .DataTypes.Photo photos = 1;
  total_size += 1 * this->photos_size();
  for (int i = 0; i < this->photos_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->photos(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Photos::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DataTypes.Photos)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Photos* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Photos>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DataTypes.Photos)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DataTypes.Photos)
    MergeFrom(*source);
  }
}

void Photos::MergeFrom(const Photos& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DataTypes.Photos)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  photos_.MergeFrom(from.photos_);
}

void Photos::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DataTypes.Photos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Photos::CopyFrom(const Photos& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DataTypes.Photos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Photos::IsInitialized() const {

  return true;
}

void Photos::Swap(Photos* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Photos::InternalSwap(Photos* other) {
  photos_.UnsafeArenaSwap(&other->photos_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Photos::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Photos_descriptor_;
  metadata.reflection = Photos_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Photos

// repeated .DataTypes.Photo photos = 1;
int Photos::photos_size() const {
  return photos_.size();
}
void Photos::clear_photos() {
  photos_.Clear();
}
const ::DataTypes::Photo& Photos::photos(int index) const {
  // @@protoc_insertion_point(field_get:DataTypes.Photos.photos)
  return photos_.Get(index);
}
::DataTypes::Photo* Photos::mutable_photos(int index) {
  // @@protoc_insertion_point(field_mutable:DataTypes.Photos.photos)
  return photos_.Mutable(index);
}
::DataTypes::Photo* Photos::add_photos() {
  // @@protoc_insertion_point(field_add:DataTypes.Photos.photos)
  return photos_.Add();
}
::google::protobuf::RepeatedPtrField< ::DataTypes::Photo >*
Photos::mutable_photos() {
  // @@protoc_insertion_point(field_mutable_list:DataTypes.Photos.photos)
  return &photos_;
}
const ::google::protobuf::RepeatedPtrField< ::DataTypes::Photo >&
Photos::photos() const {
  // @@protoc_insertion_point(field_list:DataTypes.Photos.photos)
  return photos_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace DataTypes

// @@protoc_insertion_point(global_scope)
