// Code generated by protoc-gen-go.
// source: datatypes/entity.proto
// DO NOT EDIT!

/*
Package entity is a generated protocol buffer package.

It is generated from these files:
	datatypes/entity.proto

It has these top-level messages:
	Entity
	Entities
*/
package entity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import DataTypes5 "github.com/Enebra/ServiceCoordinator/grpc/datatypes/person"
import DataTypes1 "github.com/Enebra/ServiceCoordinator/grpc/datatypes/card"
import DataTypes4 "github.com/Enebra/ServiceCoordinator/grpc/datatypes/photo"
import DataTypes7 "github.com/Enebra/ServiceCoordinator/grpc/datatypes/location"
import DataTypes8 "github.com/Enebra/ServiceCoordinator/grpc/datatypes/visitrecord"
import DataTypes9 "github.com/Enebra/ServiceCoordinator/grpc/datatypes/group"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entity struct {
	// Types that are valid to be assigned to ValueType:
	//	*Entity_Card
	//	*Entity_Person
	//	*Entity_VisitRecord
	//	*Entity_Location
	//	*Entity_Photo
	//	*Entity_Group
	ValueType isEntity_ValueType `protobuf_oneof:"value_type"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (m *Entity) String() string            { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isEntity_ValueType interface {
	isEntity_ValueType()
}

type Entity_Card struct {
	Card *DataTypes1.Card `protobuf:"bytes,1,opt,name=card,oneof"`
}
type Entity_Person struct {
	Person *DataTypes5.Person `protobuf:"bytes,2,opt,name=person,oneof"`
}
type Entity_VisitRecord struct {
	VisitRecord *DataTypes8.VisitRecord `protobuf:"bytes,3,opt,name=visit_record,json=visitRecord,oneof"`
}
type Entity_Location struct {
	Location *DataTypes7.Location `protobuf:"bytes,4,opt,name=location,oneof"`
}
type Entity_Photo struct {
	Photo *DataTypes4.Photo `protobuf:"bytes,5,opt,name=photo,oneof"`
}
type Entity_Group struct {
	Group *DataTypes9.Group `protobuf:"bytes,6,opt,name=group,oneof"`
}

func (*Entity_Card) isEntity_ValueType()        {}
func (*Entity_Person) isEntity_ValueType()      {}
func (*Entity_VisitRecord) isEntity_ValueType() {}
func (*Entity_Location) isEntity_ValueType()    {}
func (*Entity_Photo) isEntity_ValueType()       {}
func (*Entity_Group) isEntity_ValueType()       {}

func (m *Entity) GetValueType() isEntity_ValueType {
	if m != nil {
		return m.ValueType
	}
	return nil
}

func (m *Entity) GetCard() *DataTypes1.Card {
	if x, ok := m.GetValueType().(*Entity_Card); ok {
		return x.Card
	}
	return nil
}

func (m *Entity) GetPerson() *DataTypes5.Person {
	if x, ok := m.GetValueType().(*Entity_Person); ok {
		return x.Person
	}
	return nil
}

func (m *Entity) GetVisitRecord() *DataTypes8.VisitRecord {
	if x, ok := m.GetValueType().(*Entity_VisitRecord); ok {
		return x.VisitRecord
	}
	return nil
}

func (m *Entity) GetLocation() *DataTypes7.Location {
	if x, ok := m.GetValueType().(*Entity_Location); ok {
		return x.Location
	}
	return nil
}

func (m *Entity) GetPhoto() *DataTypes4.Photo {
	if x, ok := m.GetValueType().(*Entity_Photo); ok {
		return x.Photo
	}
	return nil
}

func (m *Entity) GetGroup() *DataTypes9.Group {
	if x, ok := m.GetValueType().(*Entity_Group); ok {
		return x.Group
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Entity) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Entity_OneofMarshaler, _Entity_OneofUnmarshaler, _Entity_OneofSizer, []interface{}{
		(*Entity_Card)(nil),
		(*Entity_Person)(nil),
		(*Entity_VisitRecord)(nil),
		(*Entity_Location)(nil),
		(*Entity_Photo)(nil),
		(*Entity_Group)(nil),
	}
}

func _Entity_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Entity)
	// value_type
	switch x := m.ValueType.(type) {
	case *Entity_Card:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Card); err != nil {
			return err
		}
	case *Entity_Person:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Person); err != nil {
			return err
		}
	case *Entity_VisitRecord:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.VisitRecord); err != nil {
			return err
		}
	case *Entity_Location:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Location); err != nil {
			return err
		}
	case *Entity_Photo:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Photo); err != nil {
			return err
		}
	case *Entity_Group:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Group); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Entity.ValueType has unexpected type %T", x)
	}
	return nil
}

func _Entity_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Entity)
	switch tag {
	case 1: // value_type.card
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DataTypes1.Card)
		err := b.DecodeMessage(msg)
		m.ValueType = &Entity_Card{msg}
		return true, err
	case 2: // value_type.person
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DataTypes5.Person)
		err := b.DecodeMessage(msg)
		m.ValueType = &Entity_Person{msg}
		return true, err
	case 3: // value_type.visit_record
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DataTypes8.VisitRecord)
		err := b.DecodeMessage(msg)
		m.ValueType = &Entity_VisitRecord{msg}
		return true, err
	case 4: // value_type.location
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DataTypes7.Location)
		err := b.DecodeMessage(msg)
		m.ValueType = &Entity_Location{msg}
		return true, err
	case 5: // value_type.photo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DataTypes4.Photo)
		err := b.DecodeMessage(msg)
		m.ValueType = &Entity_Photo{msg}
		return true, err
	case 6: // value_type.group
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DataTypes9.Group)
		err := b.DecodeMessage(msg)
		m.ValueType = &Entity_Group{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Entity_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Entity)
	// value_type
	switch x := m.ValueType.(type) {
	case *Entity_Card:
		s := proto.Size(x.Card)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Entity_Person:
		s := proto.Size(x.Person)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Entity_VisitRecord:
		s := proto.Size(x.VisitRecord)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Entity_Location:
		s := proto.Size(x.Location)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Entity_Photo:
		s := proto.Size(x.Photo)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Entity_Group:
		s := proto.Size(x.Group)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Entities struct {
	Items []*Entity `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *Entities) Reset()                    { *m = Entities{} }
func (m *Entities) String() string            { return proto.CompactTextString(m) }
func (*Entities) ProtoMessage()               {}
func (*Entities) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Entities) GetItems() []*Entity {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Entity)(nil), "DataTypes.Entity")
	proto.RegisterType((*Entities)(nil), "DataTypes.Entities")
}

func init() { proto.RegisterFile("datatypes/entity.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x4b, 0xc3, 0x30,
	0x1c, 0xc5, 0xbb, 0x5f, 0x75, 0x66, 0x03, 0x35, 0xea, 0x08, 0xc3, 0xc3, 0x18, 0x88, 0x03, 0xa1,
	0x45, 0x77, 0xd3, 0xdb, 0xe6, 0x58, 0x41, 0x0f, 0x12, 0x87, 0x07, 0x2f, 0x23, 0x6b, 0xc3, 0x16,
	0xd8, 0x9a, 0x92, 0x66, 0xc5, 0xfd, 0x3b, 0xfe, 0x01, 0xfe, 0x8d, 0x92, 0x6f, 0xeb, 0x1a, 0xa6,
	0xc7, 0xbe, 0xf7, 0x79, 0xe9, 0xeb, 0x6b, 0x50, 0x27, 0x62, 0x9a, 0xe9, 0x5d, 0xc2, 0x53, 0x9f,
	0xc7, 0x5a, 0xe8, 0x9d, 0x97, 0x28, 0xa9, 0x25, 0x3e, 0x7e, 0x62, 0x9a, 0xcd, 0x8c, 0xde, 0xb5,
	0x90, 0x84, 0xab, 0x54, 0xc6, 0x39, 0xd2, 0xbd, 0x28, 0xf5, 0x90, 0xa9, 0xa8, 0x50, 0x2f, 0x2d,
	0x7a, 0x25, 0xb5, 0x2c, 0x64, 0x52, 0xca, 0x6b, 0x19, 0x32, 0x2d, 0xf6, 0xc7, 0x5c, 0x95, 0x4e,
	0x26, 0x52, 0xa1, 0xe7, 0x8a, 0x87, 0xf2, 0xbf, 0xe3, 0x96, 0x4a, 0x6e, 0x93, 0x5c, 0xee, 0x7f,
	0x57, 0x91, 0x3b, 0x81, 0xbe, 0xf8, 0x1a, 0xd5, 0xcd, 0xeb, 0x49, 0xa5, 0x57, 0x19, 0xb4, 0xee,
	0x4f, 0xbc, 0x7d, 0x71, 0x6f, 0xcc, 0x54, 0x14, 0x38, 0x14, 0x6c, 0x7c, 0x8b, 0xdc, 0xbc, 0x3d,
	0xa9, 0x02, 0x78, 0x66, 0x81, 0xaf, 0x60, 0x04, 0x0e, 0x2d, 0x10, 0xfc, 0x88, 0xda, 0x76, 0x17,
	0x52, 0x83, 0x48, 0xc7, 0x8a, 0xbc, 0x1b, 0x9b, 0x82, 0x1b, 0x38, 0xb4, 0x95, 0x95, 0x8f, 0xf8,
	0x0e, 0x35, 0x7f, 0x3f, 0x91, 0xd4, 0x21, 0x78, 0x6e, 0x05, 0x5f, 0x0a, 0x2b, 0x70, 0xe8, 0x1e,
	0xc3, 0x03, 0xd4, 0x80, 0xb1, 0x48, 0x03, 0xf8, 0x53, 0xbb, 0x9b, 0xd1, 0x03, 0x87, 0xe6, 0x80,
	0x21, 0x61, 0x07, 0xe2, 0xfe, 0x21, 0xa7, 0x46, 0x37, 0x24, 0x00, 0xa3, 0x36, 0x42, 0x19, 0x5b,
	0x6f, 0xf9, 0xdc, 0xac, 0xd7, 0x1f, 0xa2, 0x26, 0xec, 0x25, 0x78, 0x8a, 0x6f, 0x50, 0x43, 0x68,
	0xbe, 0x49, 0x49, 0xa5, 0x57, 0x3b, 0x58, 0x22, 0xdf, 0x94, 0xe6, 0xfe, 0xe8, 0x19, 0x1d, 0xf1,
	0x4f, 0x6f, 0xa9, 0x92, 0xf0, 0xe3, 0x61, 0x29, 0xf4, 0x6a, 0xbb, 0xf0, 0x42, 0xb9, 0xf1, 0x27,
	0x31, 0x5f, 0x28, 0xe6, 0xbf, 0x71, 0x95, 0x89, 0x90, 0x8f, 0xa5, 0x54, 0x91, 0x88, 0x99, 0x96,
	0xca, 0x37, 0xa8, 0x7f, 0x78, 0xa3, 0xbe, 0xaa, 0x35, 0x3a, 0x9b, 0x2e, 0x5c, 0xf8, 0x73, 0xc3,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0x91, 0x4c, 0xfb, 0x72, 0x02, 0x00, 0x00,
}
