// Code generated by protoc-gen-go.
// source: services/coordinator_service.proto
// DO NOT EDIT!

/*
Package coordinatorservice is a generated protocol buffer package.

It is generated from these files:
	services/coordinator_service.proto

It has these top-level messages:
	HeartbeatMessage
*/
package coordinatorservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import DataTypes3 "github.com/Enebra/ServiceCoordinator/grpc/datatypes/unit"
import DataTypes "github.com/Enebra/ServiceCoordinator/grpc/datatypes/data"
import DataTypes1 "github.com/Enebra/ServiceCoordinator/grpc/datatypes/devices"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceType int32

const (
	ServiceType_None_Type ServiceType = 0
	ServiceType_Facial    ServiceType = 1
	ServiceType_AppUnit   ServiceType = 2
	ServiceType_Unit      ServiceType = 3
)

var ServiceType_name = map[int32]string{
	0: "None_Type",
	1: "Facial",
	2: "AppUnit",
	3: "Unit",
}
var ServiceType_value = map[string]int32{
	"None_Type": 0,
	"Facial":    1,
	"AppUnit":   2,
	"Unit":      3,
}

func (x ServiceType) String() string {
	return proto.EnumName(ServiceType_name, int32(x))
}
func (ServiceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HeartbeatMessage struct {
	ServiceId string `protobuf:"bytes,1,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
}

func (m *HeartbeatMessage) Reset()                    { *m = HeartbeatMessage{} }
func (m *HeartbeatMessage) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatMessage) ProtoMessage()               {}
func (*HeartbeatMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*HeartbeatMessage)(nil), "Services.HeartbeatMessage")
	proto.RegisterEnum("Services.ServiceType", ServiceType_name, ServiceType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for CoordinatorService service

type CoordinatorServiceClient interface {
	Connect(ctx context.Context, in *DataTypes3.ConnectedUnit, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	Heartbeat(ctx context.Context, in *HeartbeatMessage, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	GetUnits(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*DataTypes3.Units, error)
	Subscribe(ctx context.Context, in *DataTypes3.ConnectedUnit, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	Unsubscribe(ctx context.Context, in *DataTypes3.ConnectedUnit, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	Get(ctx context.Context, in *DataTypes.MessageBytes, opts ...grpc.CallOption) (*DataTypes.MessageBytes, error)
	Commit(ctx context.Context, in *DataTypes.MessageBytes, opts ...grpc.CallOption) (*DataTypes.MessageBytes, error)
	PushUpdates(ctx context.Context, in *DataTypes1.DeviceUpdate, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type coordinatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCoordinatorServiceClient(cc *grpc.ClientConn) CoordinatorServiceClient {
	return &coordinatorServiceClient{cc}
}

func (c *coordinatorServiceClient) Connect(ctx context.Context, in *DataTypes3.ConnectedUnit, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/Services.CoordinatorService/Connect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) Heartbeat(ctx context.Context, in *HeartbeatMessage, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/Services.CoordinatorService/Heartbeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) GetUnits(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*DataTypes3.Units, error) {
	out := new(DataTypes3.Units)
	err := grpc.Invoke(ctx, "/Services.CoordinatorService/GetUnits", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) Subscribe(ctx context.Context, in *DataTypes3.ConnectedUnit, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/Services.CoordinatorService/Subscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) Unsubscribe(ctx context.Context, in *DataTypes3.ConnectedUnit, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/Services.CoordinatorService/Unsubscribe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) Get(ctx context.Context, in *DataTypes.MessageBytes, opts ...grpc.CallOption) (*DataTypes.MessageBytes, error) {
	out := new(DataTypes.MessageBytes)
	err := grpc.Invoke(ctx, "/Services.CoordinatorService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) Commit(ctx context.Context, in *DataTypes.MessageBytes, opts ...grpc.CallOption) (*DataTypes.MessageBytes, error) {
	out := new(DataTypes.MessageBytes)
	err := grpc.Invoke(ctx, "/Services.CoordinatorService/Commit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) PushUpdates(ctx context.Context, in *DataTypes1.DeviceUpdate, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/Services.CoordinatorService/PushUpdates", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CoordinatorService service

type CoordinatorServiceServer interface {
	Connect(context.Context, *DataTypes3.ConnectedUnit) (*google_protobuf.Empty, error)
	Heartbeat(context.Context, *HeartbeatMessage) (*google_protobuf.Empty, error)
	GetUnits(context.Context, *google_protobuf.Empty) (*DataTypes3.Units, error)
	Subscribe(context.Context, *DataTypes3.ConnectedUnit) (*google_protobuf.Empty, error)
	Unsubscribe(context.Context, *DataTypes3.ConnectedUnit) (*google_protobuf.Empty, error)
	Get(context.Context, *DataTypes.MessageBytes) (*DataTypes.MessageBytes, error)
	Commit(context.Context, *DataTypes.MessageBytes) (*DataTypes.MessageBytes, error)
	PushUpdates(context.Context, *DataTypes1.DeviceUpdate) (*google_protobuf.Empty, error)
}

func RegisterCoordinatorServiceServer(s *grpc.Server, srv CoordinatorServiceServer) {
	s.RegisterService(&_CoordinatorService_serviceDesc, srv)
}

func _CoordinatorService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataTypes3.ConnectedUnit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Services.CoordinatorService/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Connect(ctx, req.(*DataTypes3.ConnectedUnit))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Services.CoordinatorService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Heartbeat(ctx, req.(*HeartbeatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_GetUnits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).GetUnits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Services.CoordinatorService/GetUnits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).GetUnits(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataTypes3.ConnectedUnit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Services.CoordinatorService/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Subscribe(ctx, req.(*DataTypes3.ConnectedUnit))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataTypes3.ConnectedUnit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Services.CoordinatorService/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Unsubscribe(ctx, req.(*DataTypes3.ConnectedUnit))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataTypes.MessageBytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Services.CoordinatorService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Get(ctx, req.(*DataTypes.MessageBytes))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataTypes.MessageBytes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Services.CoordinatorService/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Commit(ctx, req.(*DataTypes.MessageBytes))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_PushUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataTypes1.DeviceUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).PushUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Services.CoordinatorService/PushUpdates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).PushUpdates(ctx, req.(*DataTypes1.DeviceUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

var _CoordinatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Services.CoordinatorService",
	HandlerType: (*CoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _CoordinatorService_Connect_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _CoordinatorService_Heartbeat_Handler,
		},
		{
			MethodName: "GetUnits",
			Handler:    _CoordinatorService_GetUnits_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _CoordinatorService_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _CoordinatorService_Unsubscribe_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CoordinatorService_Get_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _CoordinatorService_Commit_Handler,
		},
		{
			MethodName: "PushUpdates",
			Handler:    _CoordinatorService_PushUpdates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("services/coordinator_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x53, 0x5d, 0x6b, 0xd4, 0x40,
	0x14, 0xdd, 0xed, 0x96, 0xdd, 0xcd, 0x5d, 0x84, 0x30, 0x88, 0x2d, 0x11, 0x41, 0xf2, 0x24, 0x3e,
	0xcc, 0xa0, 0x82, 0x20, 0x28, 0xb5, 0xdd, 0xae, 0xab, 0x0f, 0x8a, 0xb4, 0x5d, 0x1f, 0x7c, 0x59,
	0x26, 0xc9, 0x35, 0x1d, 0x68, 0x66, 0x86, 0x99, 0x1b, 0x31, 0x3f, 0xc2, 0x3f, 0xe1, 0x2f, 0x95,
	0x24, 0x53, 0x8d, 0x1f, 0xeb, 0x43, 0x7d, 0x9b, 0x9c, 0x7b, 0xee, 0x99, 0x73, 0x4f, 0xee, 0x40,
	0xea, 0xd1, 0x7d, 0x56, 0x39, 0x7a, 0x91, 0x1b, 0xe3, 0x0a, 0xa5, 0x25, 0x19, 0xb7, 0x0d, 0x20,
	0xb7, 0xce, 0x90, 0x61, 0xf3, 0xf3, 0xc0, 0x49, 0xee, 0x96, 0xc6, 0x94, 0x57, 0x28, 0x3a, 0x3c,
	0xab, 0x3f, 0x09, 0xac, 0x2c, 0x35, 0x3d, 0x2d, 0xb9, 0x5d, 0x48, 0x92, 0xd4, 0x58, 0xf4, 0xa2,
	0xd6, 0x8a, 0xfe, 0x44, 0xdb, 0x53, 0x40, 0x0f, 0x06, 0x28, 0x76, 0xda, 0x7d, 0x21, 0x7d, 0x04,
	0xf1, 0x6b, 0x94, 0x8e, 0x32, 0x94, 0xf4, 0x16, 0xbd, 0x97, 0x25, 0xb2, 0x7b, 0x00, 0xc1, 0xd0,
	0x56, 0x15, 0x87, 0xe3, 0xfb, 0xe3, 0x07, 0xd1, 0x59, 0x14, 0x90, 0x37, 0xc5, 0xc3, 0x23, 0x58,
	0x04, 0x83, 0x17, 0x8d, 0x45, 0x76, 0x0b, 0xa2, 0x77, 0x46, 0xe3, 0xb6, 0xfd, 0x88, 0x47, 0x0c,
	0x60, 0xfa, 0x4a, 0xe6, 0x4a, 0x5e, 0xc5, 0x63, 0xb6, 0x80, 0xd9, 0xb1, 0xb5, 0x1b, 0xad, 0x28,
	0xde, 0x63, 0x73, 0xd8, 0xef, 0x4e, 0x93, 0xc7, 0x5f, 0xf7, 0x81, 0x2d, 0x7f, 0x4e, 0x1f, 0xc4,
	0xd8, 0x0b, 0x98, 0x2d, 0x8d, 0xd6, 0x98, 0x13, 0x3b, 0xe4, 0xa7, 0x92, 0x64, 0xab, 0xe8, 0x79,
	0xc0, 0xb0, 0x68, 0xbb, 0x93, 0x3b, 0xbc, 0x8f, 0x84, 0x5f, 0x47, 0xc2, 0x57, 0x6d, 0x24, 0xe9,
	0x88, 0x1d, 0x43, 0xf4, 0x63, 0x12, 0x96, 0xf0, 0xeb, 0x0c, 0xf9, 0xef, 0xe3, 0xfd, 0x43, 0xe2,
	0x29, 0xcc, 0xd7, 0x48, 0xed, 0x3d, 0x9e, 0xed, 0x60, 0x25, 0xf1, 0xc0, 0x5a, 0xc7, 0x4c, 0x47,
	0xec, 0x08, 0xa2, 0xf3, 0x3a, 0xf3, 0xb9, 0x53, 0x19, 0xde, 0xd0, 0xfb, 0x62, 0xa3, 0xfd, 0x7f,
	0x49, 0x3c, 0x83, 0xc9, 0x1a, 0x89, 0x1d, 0x0c, 0x5a, 0xc3, 0xc0, 0x27, 0x0d, 0xa1, 0x4f, 0x76,
	0x15, 0xd2, 0x11, 0x7b, 0x0e, 0xd3, 0xa5, 0xa9, 0x2a, 0x75, 0xb3, 0xee, 0x97, 0xb0, 0x78, 0x5f,
	0xfb, 0xcb, 0x8d, 0x2d, 0x24, 0xa1, 0xff, 0x45, 0xe2, 0xb4, 0x5b, 0xb5, 0xbe, 0xb2, 0xdb, 0xfa,
	0xc9, 0x07, 0x98, 0xe1, 0x17, 0x5e, 0x3a, 0x9b, 0x7f, 0x5c, 0x95, 0x8a, 0x2e, 0xeb, 0x8c, 0xe7,
	0xa6, 0x12, 0x2b, 0x8d, 0x99, 0x93, 0x22, 0xfc, 0xc8, 0xc1, 0xc2, 0x88, 0x96, 0x2a, 0xfe, 0xf6,
	0x90, 0x02, 0xf6, 0x6d, 0x6f, 0x72, 0x76, 0xb1, 0xce, 0xa6, 0xdd, 0x4d, 0x4f, 0xbe, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x92, 0xfe, 0x45, 0x0a, 0x74, 0x03, 0x00, 0x00,
}
